### ISSUE TITLE
Deploy errors on Linux

### ISSUE THREAD

**Issue by quinnbailey** [DeployHubProject/DeployHub-Pro#110]
Trying to run a simple deployment on Linux with the latest build, getting an odd stack trace:

terminate called after throwing an instance of 'char const*'
Exception at line 0: dmtransfer did not execute successfully

Stacktrace:
        server centos7-clone
        dropzone 2
        deploy
        component TomcatWarDeploy
        application TomcatDeploy
        avloop
        application TomcatDeploy
        environment TestEnv
        global

Attaching debug log from running command line as well
[deploy_debug.txt](https://github.com/OpenMake-Software/ReleaseEngineer/files/251203/deploy_debug.txt)

**Comment by quinnbailey** [comment]
I recreated the server that this was deploying to and it turned out ok.  This server was created via the API, so it seems something is off with how that's happening.

**Comment by pgibbs-openmake** [comment]
What was the deployment log output? The trace output does not show the output from dmtransfer (that's written to the deployment log).

**Comment by sbtaylor15** [comment]
Need to verify that servers are created correctly via the API calls.

**Comment by quinnbailey** [comment]
I need to revisit this, but believe the issue was that the server it was trying to use had no Component Type assigned, something that's not possible from the UI.
