### ISSUE TITLE
Error parsing dmtransfer XM

### ISSUE THREAD

**Issue by quinnbailey** [DeployHubProject/DeployHub-Pro#126]
Error message seems to be missing an "L" at the end.   This one may well be difficult to recreate, as it has been inconsistent in my environment.  This deployment is executed via the API.  I periodically will see the following error come back in the deployment logging from the API, if you look for logging in the GUI you will see a completely empty deployment ... no files, logging, etc.

Error message as seen in Jenkins:

error parsing dmtransfer XM
<files><file>  <sourcedir>/tmp/tdm.284.1</sourcedir>  <targetdir>/home/omdemo/tomcat_dev/webapps</targetdir>  <filename>uptime.war</filename>  <size>0</size>  <mode>Binary</mode>  <error>Y</error>  <errortext>cp: cannot open ?/tmp/tdm.284.1/uptime.war? for reading: Permission denied<BR></errortext>  <md5></md5></file></files

**Comment by quinnbailey** [comment]
I was able to recreate the scenario via dm on the command line with debug logging, see attached.

**Comment by sbtaylor15** [comment]
dmtransfer has been rewritten.
