### ISSUE TITLE
recursive field is text, not checkbox in Quick Setup

### ISSUE THREAD

**Issue by rightker** [DeployHubProject/DeployHub-Pro#130]
Click on the Setup menu, notice that the 'recursive ' field is a text field and not a check box. Recursive should be a boolean and not a text value.

**Comment by rightker** [comment]
New Setup has been created with Recursive as a text field. Closing this issue.

**Comment by pgibbs-openmake** [comment]
Shouldn't this stay open? It needs to be a checkbox even in the new wizard (I have it on my todo list!)

**Comment by rightker** [comment]
Oh, got it backwards, reopening this.
