### ISSUE TITLE
Generic Error Message Needs More Detail

### ISSUE THREAD

**Issue by rightker** [DeployHubProject/DeployHub-Pro#143]
'Failed to Create Target Directory' is put into the log whenever a deployment takes place and either the Server is improperly named or when a Credential assigned to the Server is missing or has an invalid username/password combination. The message is confusing and RE needs a more detailed explanation of what the actual problem is.

**Comment by sbtaylor15** [comment]
Updated code to show detailed error message when a failure happens.  Fixed and tested.
