### ISSUE TITLE
Need to Replace Red and Green Icons in Applications/Timeline Tab with Bar Graph

### ISSUE THREAD

**Issue by rightker** [DeployHubProject/DeployHub-Pro#16]
Currently if there are multiple servers being deployed to during a deployment and one of them fails, the icon for that deployment shows red for a failed deployment. All of the Servers have to have been successfully deployed to in order to show a green icon. We need to come up with a bar graph to show the number of failed and successful servers to replace the current icons. This would be very helpful at a glance for admins, as well as a good selling and marketing point.

**Comment by pgibbs-openmake** [comment]
It may be a bit more complicated than that. We will have to determine if a server failure is a deployment failure or not. For example, if there are 4 web servers, the failure to deploy to 1 is not necessarily a problem. However, if there's a single web server and a single DB server, then the failure to deploy to the web server SHOULD fail the deployment. Only the customer can determine "quorum".

We could possibly do this by extending component type? Or a combination of component type and environment (what's allowed to fail in Dev may not be allowed to fail in Prod)

**Comment by rightker** [comment]
I was thinking more in terms of a quick visual reference. If everything goes perfectly, then you can see that at a glance, other wise, even if the failure was of an "insignificant" server, the user needs to know.
