### ISSUE TITLE
Need another tab on Timeline for entering operator information

### ISSUE THREAD

**Issue by rightker** [DeployHubProject/DeployHub-Pro#17]
Deploy Menu -> Applications tab -> Timeline tab -> click on a deployment in the list to bring up the Results window. It would be nice to have another tab on the Results window to put in notes, for special operations performed outside of Release Engineer, i.e. "Things went horribly wrong last night because whatsisname for got to set the flappity flaps before running this deployment", or "Be sure to set the flippity flaps before running this deployment".

**Comment by pgibbs-openmake** [comment]
There's a "comment" link on the timeline for that exact thing. Admittedly, that's not visible outside of the timeline.

**Comment by rightker** [comment]
I like a big fat tab, obvious to the thinking impaired.

**Comment by pgibbs-openmake** [comment]
It's a good idea but I doubt it'll make it into 7.6 release. Let's target it for 8.0?

**Comment by rightker** [comment]
No hurry, just wanted to put it into the system.
