### ISSUE TITLE
Need to figure out how license will be handled for Open Source version

### ISSUE THREAD

**Issue by quinnbailey** [DeployHubProject/DeployHub-Pro#179]
I'm not sure exactly how the license key is generated or how it works with the application while it's running but we need to make sure that:

  1. The open source version that we distributed has a functioning license
  2. This open source license that we distribute can't be reverse engineered in some way to allow people to use the enterprise version for free.

**Comment by sbtaylor15** [comment]
figured it out.  Implemented in SaaS and on-prem
