### ISSUE TITLE
Creating New Lifecycle Domain Creates 2 Domains

### ISSUE THREAD

**Issue by rightker** [DeployHubProject/DeployHub-Pro#208]
Click on Domain Menu -> Right-Click on Global Domain in the Tree -> Select New Sub-Domain -> Click Pencil Icon -> Rename the new Domain and Click on Contains Lifecycles Checkbox ->  Right-Click on the new Domain -> Select New SubDomain -> Notice it appears twice in the parent Domain in the tree. This only happens for the first Lifecycle Domain in the parent Domain. Others added later behave normally.

**Comment by rightker** [comment]
Same happens for Credentials. Maybe for other objects?

**Comment by pgibbs-openmake** [comment]
I have a horrible feeling this is a bug in the JSTree plugin which runs the explorer pane. The only solution to this would be to upgrade JSTree but since the entire API has changed, this would be a MAJOR piece of work.

Does this happen on all browsers?

**Comment by rightker** [comment]
Works as expected on Firefox.

**Comment by pgibbs-openmake** [comment]
So the issue is only on Chrome?

**Comment by rightker** [comment]
Only on Chrome.

**Comment by rightker** [comment]
Works on Docker ver 901.

**Comment by rightker** [comment]
It happened again on Docker ver  901, disregard previous comment.

**Comment by rightker** [comment]
Also happens with Notifier Templates.

**Comment by pgibbs-openmake** [comment]
This is probably a client side issue, shouldn't matter what back end is running. Can you confirm this is only affecting Chrome and no other browser?

**Comment by rightker** [comment]
I can't reproduce this, even on Chrome now. It happens very infrequently.
