### ISSUE TITLE
Credentials tab is missing in Connections menu

### ISSUE THREAD

**Issue by rraja002** [DeployHubProject/DeployHub-Pro#209]
Im following the tutorial and setting my first project. 
Credentials tab is missing in Connections menu
![deployhub issue 1](https://user-images.githubusercontent.com/31516920/30131990-721eda90-9314-11e7-86e0-466dd3347dc9.JPG)

**Comment by pgibbs-openmake** [comment]
Could you please confirm which browser (and version) you are using?

**Comment by rraja002** [comment]
IE and DeployHub 8.0.
btw - I tried from chrome and I can see the credentials tab now.

**Comment by sbtaylor15** [comment]
Which version of IE? 

Thanks, Steve

**Comment by rraja002** [comment]
IE 11

**Comment by pgibbs-openmake** [comment]
Just tested DeployHub Pro 8.0 with both Edge and IE11 on Windows 10 and it works okay in both (Credentials tab is displayed fine). Not sure what's happening there.

**Comment by sbtaylor15** [comment]
We will give it another test on our side with IE 11 on Windows 10 to see if we can recreate the issue.
