### ISSUE TITLE
Able to use Move Task for App Base but not Version

### ISSUE THREAD

**Issue by rightker** [DeployHubProject/DeployHub-Pro#217]
Setting up a test for moving an Application Version via a Move Task works, in that it fails when it should and works when it should, but the same test always works for an Application Version, which it shouldn't. The test involves a User with non-admin permissions having to use a Request Task to gain approval for the Move Task via an Approval Task. A User without permission to use the Move Task can use it to move an Application Base Version but not an Application Version. See the steps below:

Create a Move Task that moves an Application Version from the current Domain to another Domain. Assign Access to a Group that contains a User who does not have admin rights, as well as the admin Group.
Create a Request Task that has the Move Task as the Linked Task, and assign the same Group that contains a User who does not have admin rights.
Create an Approve Task that only has admin as the User Group, and set the Approval Domain as the target Domain where the Application Version will be moved. (Only Application Versions can be moved, not Application Base Versions).
Sign in as the non-admin User and try to run the Move Task, it should fail.
Run the Request Task.
Sign out and back in as admin, run the Approve Task.
Sign out and back in as the non-admin User.
Run the Move Task, it should succeed.

**Comment by pgibbs-openmake** [comment]
There should be no difference between Application Base and Application Versions as far as "Move" is concerned. Both can be moved between domains if they are approved for that target domain and the user has permission to instigate the move.

I'm struggling with the last steps of this. What you're describing is how this works. In other words, an administrator approves the application for a target domain and once this is done the non-admin user can then perform the move. The "request" bit is just flim-flam and not relevant. When you say "it should succeed", you're right - it should. Are you saying it isn't?

**Comment by rightker** [comment]
I'm saying that I can move an Application Base Version when I'm logged in as a User without permission to do so, but I can't move an Application Version as the same User, which is the correct behaviour. Why does one get moved and the other one doesn't, when the User has no permissions to do either, unless granted so by an Approval Task?

**Comment by rightker** [comment]
It turns out that if an App Base or App Version is Approved, it is Approved and can be Moved between folders until it is Rejected. Will remove this from the test results document  P:\shared\Google Drive\Shared Area\ReaseEngineer8.0Testing but leave open until written into in the online docs.
