### ISSUE TITLE
Cannot create a Component Item

### ISSUE THREAD

**Issue by VinaykumarEndla** [DeployHubProject/DeployHub-Pro#228]
Hi,

I just installed DeployHub Open source version 8.0.1 in Windows machine. Whenever I am trying to create a component item by right-clicking on Deploy -> Component Items screen, I see no dialog box coming. Sometimes, I see the "Loading" grey screen showing up but eventually stuck on the same scree.

Can someone help me in this regard? Also let me know where can I check logs for the tool in case required.

Thanks,
Vinaykumar Endla

**Comment by pgibbs-openmake** [comment]
Found the issue - this has just been introduced by the new object name check. Object names are no longer allowed to have spaces. When a Component Item is first created its name defaults to "Item 1" which fails the internal name check.

New build on its way.

**Comment by pgibbs-openmake** [comment]
New version of DeployHubPro.msi is on the website.

www.openmakesoftware.com/re/DeployHubPro.msi

This fixes the issue.

FYI the log file for the Web UI is recorded in:

 C:\Program Files\Openmake Software\DeployHub\WebAdmin\log
