### ISSUE TITLE
Base directory check failing

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#238]
Base directory "/" is invalid or inaccessible /opt/deployhub/engine/lib/sshexec: line 84: /home/omreleng/.ssh/known_hosts.unique: Permission denied
/opt/deployhub/engine/lib/sshexec: line 85: /home/omreleng/.ssh/known_hosts: Permission denied
/opt/deployhub/engine/lib/sshexec: line 88: /home/omreleng/.ssh/known_hosts.unique: Permission denied
cat: /home/omreleng/.ssh/known_hosts: Permission denied
/opt/deployhub/engine/lib/sshexec: line 89: /home/omreleng/.ssh/known_hosts: Permission denied
grep: /home/omreleng/.ssh/known_hosts: Permission denied
/opt/deployhub/engine/lib/sshexec: line 97: /home/omreleng/.ssh/known_hosts.unique: Permission denied
/opt/deployhub/engine/lib/sshexec: line 98: /home/omreleng/.ssh/known_hosts: Permission denied
load pubkey "/home/omreleng/.ssh/id_rsa": Permission denied 
load pubkey "/home/omreleng/.ssh/id_rsa": Permission denied 
load pubkey "/home/omreleng/.ssh/id_dsa": Permission denied 
load pubkey "/home/omreleng/.ssh/id_dsa": Permission denied 
load pubkey "/home/omreleng/.ssh/id_ecdsa": Permission denied 
load pubkey "/home/omreleng/.ssh/id_ecdsa": Permission denied 
load pubkey "/home/omreleng/.ssh/id_ed25519": Permission denied 
load pubkey "/home/omreleng/.ssh/id_ed25519": Permission denied 
load pubkey "/home/omreleng/.ssh/id_xmss": Permission denied 
load pubkey "/home/omreleng/.ssh/id_xmss": Permission denied

**Comment by sbtaylor15** [comment]
Can you please login into the container and send me the output from:

ls -ld /home/omreleng/.ssh

and 

ls -l /home/omreleng/.ssh

**Comment by piyush94** [comment]
Thanks, It's working now.
