### ISSUE TITLE
migrate data from OSS postgreSQL to the PRO

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#239]
Is there a way to migrate data from postgresql?

**Comment by sbtaylor15** [comment]
We need to do an export using Windows pgAdmin tool.  In the pgAdmin, navigate to the postgres database and dm schema.  Right click and select backup.  Use Plain for the format.  On the Dump options, select pre-data, post-data and data.  Also, select "Use Insert Commands".  Send me the exported file as a zip.  I want to load it into my db first to check that everything get migrated correctly.  Pro has more tables and new columns that I want to verify that they get added in conjunction with your data.

**Comment by piyush94** [comment]
Backup file:
[DH_OSS_Backup.zip](https://github.com/DeployHubProject/DeployHub-Pro/files/3036959/DH_OSS_Backup.zip)

**Comment by sbtaylor15** [comment]
Can you send me a zip of the data directory that is being mounted on the docker run command?  I can verify that the migration of the tables works using the low level database files.

**Comment by sbtaylor15** [comment]
The docker containers will migrate the persistent storage from OSS schema to the Pro schema.  But you cannot go from the Pro to OSS.
