### ISSUE TITLE
login failing for new user created from API

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#240]
![image](https://user-images.githubusercontent.com/11614204/55392299-a1b53080-5558-11e9-9eeb-fb90b8796e8b.png)

**Comment by piyush94** [comment]
API: http://host:8080/dmadminweb/API/new/user/demouser?realname=User, Demo&pw=password&cpw=y&user=admin&pass=admin

**Comment by sbtaylor15** [comment]
How did you call the API via curl or another way?  Please send me the command that you used.

**Comment by piyush94** [comment]
curl --request POST \
  --url 'http://<host>:8080/dmadminweb/API/new/user/demouser?realname=User%2C%20Demo&pw=password&cpw=y&user=admin&pass=admin' \
  --cookie JSESSIONID=9F846CFE77C310BD112476636C10891C

**Comment by sbtaylor15** [comment]
Fixed the login issue when a force password change was needed.  The password change was not logging in with the username and old password so the userid was not found for the update.  Passed testing.  Run _docker pull quay.io/deployhub/deployhub-pro_ to get the update.

**Comment by piyush94** [comment]
Thanks, working now.
