### ISSUE TITLE
unable to mount logs folder

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#241]
![image](https://user-images.githubusercontent.com/11614204/55536500-90466280-56d7-11e9-94f5-9d52d5215549.png)

**Comment by sbtaylor15** [comment]
Remove the -v ~/logs:/opt/deployhub/logs:Z parameter.  The host file system does not have the correct permissions for DeployHub to write the log files.  The log files will be kept in the container file system instead.
  
Run the following to get the logs:  
`docker exec {container id}  cat /opt/deployhub/logs/deployhub.log`

**Comment by piyush94** [comment]
ok
