### ISSUE TITLE
unable to deploy to windows endpoint

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#243]
ERROR: Failed to Deploy File wildfly-10.1.0.Final.tar.gz -> USTR-UVM-12191:c:\temp\wildfly-10.1.0.Final.tar.gz: No such file or directory 0\

**Comment by sbtaylor15** [comment]
I changed the underlying code to push up details on my the deployment is failing.  
Please pull the latest image.

`docker pull quay.io/deployhub/deployhub-pro`

**Comment by piyush94** [comment]
getting this error now:
![image](https://user-images.githubusercontent.com/11614204/55700997-2e476f00-59ef-11e9-891b-b0635d7c85cc.png)

**Comment by sbtaylor15** [comment]
Looks like WimRM is not enabled on the window box.  Let me hunt down the link to the doc on how to enable it.

**Comment by piyush94** [comment]
Thanks. It's working now.
