### ISSUE TITLE
not able to create new endpoint type as a non-admin user

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#246]
non-admin group access rights
![image](https://user-images.githubusercontent.com/11614204/55935188-98ab1a00-5c50-11e9-8aba-70dbb7249581.png)

**Comment by piyush94** [comment]
But after creating from admin, i am able to modify the object.

**Comment by sbtaylor15** [comment]
That screen is for the overall creation rights.  It does not control the detailed access control around each object, end-points, applications, components, domains etc.  Each object has its own access control.  Select an object, ie end point, and go to the Access Tab.  Set the Group access for the object.  That should resolve your issue.

**Comment by piyush94** [comment]
The issue is if a user is not in admin group, and goes to domains -> component and end point types -> right click on domain of which user is part of but still add new menu is not coming.

**Comment by sbtaylor15** [comment]
Have you modified the Creation Rights for that user or users group?  Or just using the defaults?

**Comment by piyush94** [comment]
Gave all the creation rights to the group of which user is part of. That is the image in my first comment.

**Comment by sbtaylor15** [comment]
Got it.  Let me try to recreate the issue.

**Comment by piyush94** [comment]
Hi Steve,
Any update on this issue. This is currently a roadblock in providing non-admin access to users. Kindly revert ASAP.
Regards, Piyush

**Comment by sbtaylor15** [comment]
@piyush94 - Please pull the latest image (build 1455), `docker pull quay.io/deployhub/deployhub-pro`  

Added a new checkbox (Server and Component Types) on the Creation Rights for a group.  As admin, check the Server and Component Types, then logoff and back in as non-admin.  You should now have the menu item to create component types.

CC: @svisagan8

**Comment by piyush94** [comment]
The view is not scrollable, so the new option is getting hidden.
![image](https://user-images.githubusercontent.com/11614204/61767873-37741480-ae03-11e9-9f8a-2f12729bcb84.png)

**Comment by sbtaylor15** [comment]
Changed the panel sizing so the Servers & Component Types are not cut off.
Please pull the latest image.

CC: @svisagan83

docker sha256:cf186b1ee1ff23860d8e7fdcc6a90bdbb8f50fff2e79269c1c904be8c617e034

**Comment by piyush94** [comment]
@sbtaylor15 Thanks, it's fixed now.
CC: @svisagan83
