### ISSUE TITLE
Export option on reports not working

### ISSUE THREAD

**Issue by svisagan83** [DeployHubProject/DeployHub-Pro#247]
On the Global Reports Section, the Reports are displayed properly. but when we click on the export options (Excel, Xml, csv, pdf) an error page is displayed 

![image](https://user-images.githubusercontent.com/19646628/56633230-e07f6780-667a-11e9-9a37-a4cfb7714461.png)

**Comment by sbtaylor15** [comment]
Replaced reporting libraries with DataTables OSS.  Rebuilt and tested to make sure exports are working correctly.  Grab the latest image.

`docker pull quay.io/deployhub/deployhub-pro:latest`
