### ISSUE TITLE
Too many log files in tmp directory

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#248]
Deployhub is creating too many ansible log files in the tmp directory in the container.
Screenshot attached.
![image](https://user-images.githubusercontent.com/11614204/61611313-1b446c00-ac79-11e9-839f-5e776c784823.png)

**Comment by sbtaylor15** [comment]
A quick work around is to disable the Auto Ping and Auto MD5 check for each end point. We will make a change on the backend to cleanup the files.

**Comment by sbtaylor15** [comment]
Added delete step for the ansible log files.  Please pull the latest image. `docker pull quay.io/deployhub/deployhub-pro`

CC: @svisagan83

docker sha256:08138eb0d5208c26a55ecc31713322e2ca2c7c421ee0f154b482779d8c917163

**Comment by piyush94** [comment]
@sbtaylor15 Thanks.
CC: @svisagan83
