### ISSUE TITLE
ftp repo error, ftp.dll missing

### ISSUE THREAD

**Issue by sbtaylor15** [DeployHubProject/DeployHub-Pro#249]
![image](https://user-images.githubusercontent.com/14826572/61647823-63f52880-ac6b-11e9-88d8-de32259b16e1.png)

@piyush94 which install of DeployHub is this from, the on-prem docker version?

Also, what is the Target OS, Window 2016 Server?

**Comment by piyush94** [comment]
Deployhub is on prem docker version.
Target is windows server 2016.

**Comment by piyush94** [comment]
@sbtaylor15 Any update regarding this?
CC: @svisagan83

**Comment by sbtaylor15** [comment]
Error message was stating that the wrong share library was not be loaded correctly.  Cleaned up message and added library to the LD_LIBRARY_PATH in the container so it is picked up and loaded correctly.

CC: @svisagan83

docker pull quay.io/deployhub/deployhub-pro@sha256:982c40417b54d57250fd874e15548d40ddfc7c780f43a09097714de73ca98835

**Comment by piyush94** [comment]
Thanks, it's working now.
CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 One small issue, during deployment the repo filepath for file is being created in the endpoint.
Instead of only copying the file to target directory, it's also replicating the ftp directory structure on the endpoint.
![image](https://user-images.githubusercontent.com/11614204/62108747-70f7c480-b2c8-11e9-870d-721207e3039e.png)
![image](https://user-images.githubusercontent.com/11614204/62108777-84a32b00-b2c8-11e9-8980-04709d78371e.png)
![image](https://user-images.githubusercontent.com/11614204/62108824-9b498200-b2c8-11e9-918a-33294bb91615.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - Changed the ftp repo to checkout to a single directory instead.  Test several different scenarios and working as expected.

CC: @svisagan83

docker pull quay.io/deployhub/deployhub-pro@sha256:982c40417b54d57250fd874e15548d40ddfc7c780f43a09097714de73ca98835

**Comment by piyush94** [comment]
@sbtaylor15 Now it's just ignoring filepath
![image](https://user-images.githubusercontent.com/11614204/62192272-e7f98f80-b392-11e9-9c5e-f1f67236703f.png)

![image](https://user-images.githubusercontent.com/11614204/62192168-bbde0e80-b392-11e9-9dd9-a43890379262.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - File match was off when just the / was used at the repository filepath property.  Corrected matching code.

CC: @svisagan83

docker pull quay.io/deployhub/deployhub-pro@sha256:29bf817fc3f068fd48d7c7623cd4917ebade546e5034eedf84981f4aa76e105d

**Comment by sbtaylor15** [comment]
@piyush94 - Is this now working the way you expect the files to be transfer?

**Comment by piyush94** [comment]
@sbtaylor15 It's working now. Only thing is it's not displaying the full path in logs.
![image](https://user-images.githubusercontent.com/11614204/62345593-8d863d80-b510-11e9-89a9-7c8b65c321b5.png)

CC: @svisagan83
