### ISSUE TITLE
powershell script as function not working

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#252]
**Scenario**:
![function](https://user-images.githubusercontent.com/11614204/61938947-dc335500-afaf-11e9-8d3c-65ae9ffbf47d.PNG)

![action](https://user-images.githubusercontent.com/11614204/61938960-e0f80900-afaf-11e9-8aa2-c87b4d49bf86.PNG)

![dmscript](https://user-images.githubusercontent.com/11614204/61938963-e2c1cc80-afaf-11e9-9944-62715be13348.PNG)

**Error**:
PLAY [Execute File] ************************************************************

TASK [Execute File] ************************************************************
fatal: [ustr-uvm-12271.na.uis.unisys.com]: FAILED! => {"changed": false, "cmd": "C:\\temp\\examplescript.ps1 code", "msg": "Exception calling \"RunCommand\" with \"5\" argument(s): \"Failed to create new process (%1 is not a valid Win32 application, Win32ErrorCode 193)\"", "rc": 2}
 to retry, use: --limit @/tmp/tmpz2vc6t3n/runit.retry

PLAY RECAP *********************************************************************
ustr-uvm-12271.na.uis.unisys.com : ok=0    changed=0    unreachable=0    failed=1

**Comment by piyush94** [comment]
CC: @svisagan83

**Comment by sbtaylor15** [comment]
What output do the powershell program return, json?

**Comment by piyush94** [comment]
The script is not returning anything. We assumed that in the result variable, the exit code of the script will be captured. Does it work this way or we have to explicitly return a value?
Again main issue is that script is not getting executed if arguments are passed, even if nothing is returned.
Also if we use named parameters like `script.ps1 -appName "code"`, it throws below error:
```
Usage: dmtransfer [OPTIONS] [EXEC]... 

Try "dmtransfer --help" for help. 

Error: no such option: -a
```

**Comment by sbtaylor15** [comment]
Let me check on the passing back of the return code to the DM Script.  I know that json output from the script is automatically parsed into DM Script variables.

**Comment by sbtaylor15** [comment]
The non-zero return code from the powershell script causes an exception to be thrown in the DMScript.  This exception needs to be caught and transformed into a return code. 

I am working on an example of how this should be structured.

**Comment by piyush94** [comment]
script:
```
param (
    [Parameter(Mandatory=$true)]
    [string]$AppName
)

$app = Get-WmiObject -Class Win32_Product | Where-Object { 
    $_.Name -like $AppName
}

if($null -eq $app) {
	Write-Output "false"
    # exit 0
} else {
	Write-Output "true"
    # exit -1
}
```

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - The latest image has the fix.  Here are screen shots for configuring the Action.

```
param (
    [Parameter(Mandatory=$true)]
    [string]$AppName
)

$app = Get-WmiObject -Class Win32_Product | Where-Object {
    $_.Name -like $AppName
}

if($null -eq $app) {
        Write-Output "0"
    # exit 0
} else {
        Write-Output "1"
    # exit -1
}
```

![image](https://user-images.githubusercontent.com/14826572/62165809-7ced8180-b2dc-11e9-82bf-08e9212d0ad9.png)
![image](https://user-images.githubusercontent.com/14826572/62165867-9db5d700-b2dc-11e9-80b1-2c172d589632.png)
![image](https://user-images.githubusercontent.com/14826572/62165883-a9090280-b2dc-11e9-9e06-90944566e347.png)
![image](https://user-images.githubusercontent.com/14826572/62165909-b58d5b00-b2dc-11e9-9a19-b751dbe9df5a.png)
![image](https://user-images.githubusercontent.com/14826572/62165924-c0e08680-b2dc-11e9-937b-f92a8229afcf.png)
![image](https://user-images.githubusercontent.com/14826572/62165952-d190fc80-b2dc-11e9-9473-b0e5cffd212a.png)
![image](https://user-images.githubusercontent.com/14826572/62165973-df468200-b2dc-11e9-8b23-5237a4bbc823.png)


CC: @svisagan83


docker pull quay.io/deployhub/deployhub-pro@sha256:7b4c3289a8b692b4e9817dfad4846b51233a266399c7e63acd20e6799a99035d

**Comment by piyush94** [comment]
@sbtaylor15 No luck, still not working.
```
param (
    [Parameter(Mandatory=$true)]
    [string]$AppName
)

$app = Get-WmiObject -Class Win32_Product | Where-Object { 
    $_.Name -like $AppName
}

if($null -eq $app) {
	Write-Output "false"
    # exit 0
} else {
	Write-Output "true"
    # exit -1
}
```

![image](https://user-images.githubusercontent.com/11614204/62189775-81be3e00-b38d-11e9-8e79-05a03609ccfa.png)
![image](https://user-images.githubusercontent.com/11614204/62189790-8b47a600-b38d-11e9-9ba1-540afaa9c9c7.png)
![image](https://user-images.githubusercontent.com/11614204/62189809-94d10e00-b38d-11e9-8aa9-241de32e848d.png)
![image](https://user-images.githubusercontent.com/11614204/62189818-9a2e5880-b38d-11e9-8fba-1280b65e4807.png)


```
PLAY [Execute File] ************************************************************

TASK [Execute File] ************************************************************
fatal: [USTR-UVM-12271.na.uis.unisys.com]: FAILED! => {"changed": false, "cmd": "C:\\temp\\examplescript.ps1 -appName code", "msg": "Exception calling \"RunCommand\" with \"5\" argument(s): \"Failed to create new process (%1 is not a valid Win32 application, Win32ErrorCode 193)\"", "rc": 2}
 to retry, use: --limit @/tmp/tmp8mhz91fc/runit.retry

PLAY RECAP *********************************************************************
USTR-UVM-12271.na.uis.unisys.com : ok=0    changed=0    unreachable=0    failed=1 
```
Reference: https://github.com/ansible/ansible/issues/45107

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Found a workaround:
![image](https://user-images.githubusercontent.com/11614204/62190455-03fb3200-b38f-11e9-862c-cf77e8647062.png)
This is working.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - Added code to default the necessary command shell if one is not supplied.

.ps1 = powershell.exe -File
.vbs = cscript.exe /nologo
.js    = cscript.exe /nologo
.wsf = cscript.exe /nologo

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - please remove your work around and let us know if the default is used.

**Comment by piyush94** [comment]
@sbtaylor15 Not working without workaround
```
PLAY [Execute File] ************************************************************

TASK [Execute File] ************************************************************
fatal: [USTR-UVM-12271.na.uis.unisys.com]: FAILED! => {"changed": false, "cmd": "C:\\temp\\examplescript.ps1 -appName Zoom", "msg": "Exception calling \"RunCommand\" with \"5\" argument(s): \"Failed to create new process (%1 is not a valid Win32 application, Win32ErrorCode 193)\"", "rc": 2}
 to retry, use: --limit @/tmp/tmpyik2mmzf/runit.retry

PLAY RECAP *********************************************************************
USTR-UVM-12271.na.uis.unisys.com : ok=0    changed=0    unreachable=0    failed=1 
```

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - Added default shell for scripts that exists already on remote end point.
CC: @svisagan83

docker pull quay.io/deployhub/deployhub-pro@sha256:df5cb2331491717d5ea1a08109794a88b659264e1088d8225930c3948176113c

**Comment by piyush94** [comment]
@sbtaylor15 It'sworking now.

CC: @svisagan83
