### ISSUE TITLE
Jenkins groovy issue

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#255]
[jenkins_log.txt](https://github.com/DeployHubProject/DeployHub-Pro/files/3452085/jenkins_log.txt)

[Jenkinsfile.txt](https://github.com/DeployHubProject/DeployHub-Pro/files/3452107/Jenkinsfile.txt)

**Comment by sbtaylor15** [comment]
@piyush94 - I simplified the groovy code to make the component variant optional.  Here is a snippet of the code I was testing with.  This is inline with the versioning format that you are currently using.

You will need to fully qualify the component name using a dot between each domain level.  This is needed so we can place the component in the correct domain.  

```
      def compname = "GLOBAL.American University.CSC589.chili.Uptime Dashboard XXX";
      def compvariant = "";
      def compversion = "v1.5.0";
	    
      data = dh.newComponentVersion(url,user,pw, compname, compvariant, compversion);
      echo data.toString();
      def attrs = [buildnumber: env.BUILD_ID];
      data = dh.updateComponentAttrs(url,user,pw, compname, compvariant, compversion ,attrs);
      echo data.toString();
```

Please delete old components from the DeployHub UI and start fresh.  I tested the following scenarios:

1. No component exists - results in new base version and version 1 with the job number associated to version 1
2. Rerun the same pipeline without any changes - results in version 1 having the job number updated
3. Use "July Release" as Component Variant and Component Version = "v1.5.0-" + env.BUILDID - results in new base version and version 1 with the job number associated to version 1 and version =  v1_5_0_1260
4. Rerun test 3 - results in version 2 with the job number associated to version 2 and version =  v1_5_0_1261

**Comment by sbtaylor15** [comment]
CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 I am still not able to create version and update attributes.

**Jenkinsfile**
```
def comp="GLOBAL.Test_Project.Test.testapp"
// def app="AppUI_Helm"
def environment="ustr-k8s"
// def cmd=""
def url="https://us-deployhub.na.uis.unisys.com:7171"
def user="dhguest"
def pw="Sing*2011"
echo "${url}";
echo "${version}";

// create component version
// def newComponentVersion(String url, String userid, String pw, String compname, String compvariant, String compversion)
data = dh.newComponentVersion(url, user, pw, comp, "", version);
echo "Creation Done " + data.toString();

// // update attrs
def attrs = [Chart: "harbor-lib/"+imagename, buildnumber: env.BUILD_ID, chartversion: version];
echo "${attrs}";
// // def updateComponentAttrs(String url, String userid, String pw, String compname, String compvariant, String compversion, Map Attrs)
data = dh.updateComponentAttrs(url, user, pw, comp, "", version , attrs);
echo "Update Done " + data.toString();
```

**Jenkins Log**
```
[Pipeline] stage
[Pipeline] { (Deploy)
[Pipeline] echo
https://us-deployhub.na.uis.unisys.com:7171
[Pipeline] echo
0.1.0-103
[Pipeline] echo
Creation Done 141
[Pipeline] echo
[Chart:harbor-lib/app-ui-helm, buildnumber:103, chartversion:0.1.0-103]
[Pipeline] echo
Update Done null
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```
**I have created a new component for the testing**
![image](https://user-images.githubusercontent.com/11614204/62294065-c9c18b80-b487-11e9-90db-11e4efc05797.png)

Am i missing something?

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Did testapp exist already before you ran your pipeline or did it get created?

**Comment by sbtaylor15** [comment]
@piyush94 - how do you have the security setup for dhguest?

**Comment by sbtaylor15** [comment]
@piyush94 -  The chartversion was causing issues.  We added that in as a special attribute to catch and push to the docker component item once we recognized that helm needed the chart version passed in as a parameter.

Please pull the latest image.

CC: @svisagan83

 docker pull quay.io/deployhub/deployhub-pro@sha256:e556ab9441d46ef1067f8507b14a62633aaa1e24cc4ffd87cda7dd83382d5547

**Comment by piyush94** [comment]
@sbtaylor15 I had created the testapp base version from the WebApp.
dhguest has creation rights for components, versions and applications.

**Comment by sbtaylor15** [comment]
Delete the testapp component and let the Jenkins pipeline create it.  The pipeline should create testapp and testapp;0_1_0_103.  testapp;0_1_0_103 should have the lastbuild number set and the docker component item should have the chart and chart version listed.

**Comment by piyush94** [comment]
@sbtaylor15  not working
```
def comp="Global.Demo.testapp";
def environment="demoenv";
// def cmd=""
def url="http://ustr-uvm-12703.na.uis.unisys.com:8383";
def user="admin";
def pw="admin";
    
    echo env.BUILD_ID;
    echo "$url";
    
    
    def version = "v1.5.0";
    echo "$version";
    // create component version
                // def newComponentVersion(String url, String userid, String pw, String compname, String compvariant, String compversion)
                data = dh.newComponentVersion(url, user, pw, comp, "", version);
                echo "Creation Done " + data.toString();

                // // update attrs
                def attrs = [Chart: "harbor-lib/"+imagename, buildnumber: env.BUILD_ID, chartversion: version];
                echo "${attrs}";
                // // def updateComponentAttrs(String url, String userid, String pw, String compname, String compvariant, String compversion, Map Attrs)
                data = dh.updateComponentAttrs(url, user, pw, comp, "", version , attrs);
                echo "Update Done " + data.toString();
```
**Error:**
```
java.lang.NullPointerException: Cannot get property 'id' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:456)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at deployhub.newComponent(/var/lib/jenkins/jobs/DH_POC/jobs/AppUI_Helm/builds/26/libs/deployhub/vars/deployhub.groovy:493)
	at deployhub.newComponentVersion(/var/lib/jenkins/jobs/DH_POC/jobs/AppUI_Helm/builds/26/libs/deployhub/vars/deployhub.groovy:564)
	at WorkflowScript.run(WorkflowScript:30)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor546.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:136)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by piyush94** [comment]
@sbtaylor15 It is working now. But i have some doubts:
1. Do we not have to set component attributes anymore for helm charts, if we have a docker item with details like this:
![image](https://user-images.githubusercontent.com/11614204/62352434-c381ec80-b525-11e9-8d63-15a4d71a358a.png)
2. Is the above item working?
3. Does the create new version step applicable to existing components?
4. How do we set the new component version in the application and do deploy?

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Need to inherit from base version or latest
- Build Job
- Component Type
- Actions
- Deploy Always

**Comment by sbtaylor15** [comment]
List of Attributes for component and component item

**Comment by sbtaylor15** [comment]
**Attributes and properties for the component**

- BuildId - build id from the build system such as Quay
- BuildUrl - build url for the build system
- Chart - helm chart for the component 
- ChartVersion - version of the helm chart
- operator - Kubernetes operator
- DockerBuildDate - timestamp for the docker build
- DockerSha - sha for the docker image
- DockerRepo - url for the docker registry
- GitCommit  - git commit that trigger the build
- GitRepo - git repo name
- GitTag - git tag such as master or v1.5.0
- GitUrl - url to the git repo
- buildnumber - build job number for Jenkins
- buildjob - build job name for Jenkins
- ComponentType - name of the component type
- ChangeRequestDS - name of the Change Request Datasource
- Category - name of the components category
- AlwaysDeploy - Y/N
- DeploySequentially - Y/N
- BaseDirectory - base directory for the component
- PreAction - name of the pre-action
- PostAction - name of the post-action
- CustomAction - name of the custom-action

**Comment by sbtaylor15** [comment]
```
// // update attrs
def attrs = [
	     BuildId: env.BUILD_ID,
	     BuildUrl: env.BUILD_URL,
             Chart: "harbor-lib/"+imagename, 
	     chartversion: version,
	     operator: "Kubernetes operator",
	     DockerBuildDate: "timestamp",
	     DockerSha: "sha for the docker image",
	     DockerRepo: "url for the docker registry",
	     GitCommit: "git commit",
	     GitRepo: "git repo",
	     GitTag: "git tag",
	     GitUrl: "git url",
	     buildnumber: env.BUILD_ID, 
	     buildjob: "GLOBAL.test-project",
	     ComponentType: "Wildfly_EP",
	     ChangeRequestDS: "GLOBAL.JiraUnisys",
	     Category: "General",
	     AlwaysDeploy: "N",
	     DeploySequentially: "N",
	     BaseDirectory: "tmp",
	     PreAction: "GLOBAL.Run_SQL_Script_Postgres",
	     PostAction: "GLOBAL.Run_SQL_Script_Postgres",
	     CustomAction: "GLOBAL.Run_SQL_Script_Postgres",
	     Summary: "Pipeline Comp"
	    ];
echo "${attrs}";
// // def updateComponentAttrs(String url, String userid, String pw, String compname, String compvariant, String compversion, Map Attrs)
data = dh.updateComponentAttrs(url, user, pw, comp, "", version , attrs);
```

**Comment by sbtaylor15** [comment]
The latest image has the updated for setting all of attributes listed above.  Next step is to add logic to the groovy library for passing in Component Item Type (docker/non-docker items).

docker pull quay.io/deployhub/deployhub-pro@sha256:2a086f6c36f63c73d2c810f59545a5a498c4dfbdf7ed4b3eb5dbd218c06090d6

**Comment by sbtaylor15** [comment]
@piyush94 chartnamespace can now be passed as an attribute.

**Comment by sbtaylor15** [comment]
@piyush94 here is an example that creates the application version, assigns the application to an environment, and adds component versions to the application.

https://github.com/DeployHubProject/Uptime-Jenkins-Pipeline/blob/master/Jenkinsfile

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 it is trying to roll forward from 1_0_42 to 1_0_43 and the 2 versions are unrelated so it can't figure out how to do the roll forward.  I believe there is a flag we can set to clear this up.  The other way is to make 1_0_43 be a child of 1_0_42.  Goto the base version of the application and then to the Application Versions tab and send a screen shot.  I believe both versions come from the "start" instead of 1_0_43 being related to 1_0_42.

**Comment by piyush94** [comment]
@sbtaylor15 I don't have the screenshot now, because i deleted that application. But, yes, both versions came from "start". And i think it would be ok to prevent roll forward for helm charts. Let me know how to prevent this.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94  From the Jenkinsfile use  `forceDeployIfNeeded(String url, String userid, String pw, String Environment)` before doing the deployment.  This will tell DeployHub to forget the current version that is deployed to the environment enabling any version to be deployed.

Let me know if you need to reset via the UI since there are multiple steps that need to be done.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 getting this error:
![image](https://user-images.githubusercontent.com/11614204/64758446-3d0ff000-d552-11e9-8124-d13fc4ac454c.png)

It's asking me to approve the script execution:
![image](https://user-images.githubusercontent.com/11614204/64758490-544edd80-d552-11e9-8289-c239d911c091.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Hi Steve, is the creation of non docker component working from the groovy library. If it is, can you share a sample Jenkinsfile.
Thanks.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we added the logic for the new application version to be derived from the latest.  Make sure to set the Component Deploy Always to "N", this will tell DeployHub to skip the roll forward unless the components don't exist for the environment.

Need to discuss what is meant by "latest".

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Hi, for now "latest" can be latest application version available in the domain.
Thanks.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Regarding your comment, do i need to change anything in the script to derive application version from latest version?
Thanks.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 no changes are needed.  

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we added the ability to handle multiple component items for non-docker components.  See https://github.com/DeployHubProject/Uptime-Jenkins-Pipeline/blob/master/JenkinsfileMulti for an example.

```
      def component_items = [
       [name: 'file 1', repo: 'GLOBAL.Global_Repo', uri: '/jobs', pattern: 'file11.txt'],
       [name: 'file 2', repo: 'GLOBAL.USTR-NEXUS-1', uri: '/nexus', pattern: 'file12.jar']
      ];
       echo "${component_items}";
	    
      // create component version
      compid = dh.newComponentVersion(url, user, pw, comp, "", version, "file",component_items);
      echo "Creation Done " + compid.toString();
```

FYI, I need to still add the links between the component items.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 the uri is not getting updated in the component items.
![image](https://user-images.githubusercontent.com/11614204/65122279-2d8b1e00-da0e-11e9-98a2-29406262f988.png)

![image](https://user-images.githubusercontent.com/11614204/65122307-3aa80d00-da0e-11e9-86dd-1499f4d88d29.png)

Thanks.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 And also one more field for component item is required i.e. "Target Directory".
Thanks.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Let me check on the URI since it is the only uppercase parameter.  Did you update to the latest docker image?

Also I will add target directory.

**Comment by piyush94** [comment]
I have not updated the docker image yet. Is it required for this?

**Comment by sbtaylor15** [comment]
Yes, I made a change for the URI.

**Comment by piyush94** [comment]
@sbtaylor15 Hi Steve, we are getting this error when deploying after updating the image to latest:
```Runtime error: Select for update failed Unhandled exception: Failed to finish audit recording```

It's followed by this error:
![image](https://user-images.githubusercontent.com/11614204/65251756-87c2d680-db15-11e9-9fa4-d39d0865a471.png)

We have a modified jssecacerts file mounted into the jre folder with our certificates.

Any idea what can be the issue?
Thanks.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Also what would be a better way to keep backup of the pgsql from our side?
Either pg_dumpall or copy of the pgsql folder mount?

Thanks,

**Comment by sbtaylor15** [comment]
@piyush94 Use pg_dumpall if you want to backup while the container is running.  Otherwise if the container is stopped you can backup the pgsql host folder.

**Comment by sbtaylor15** [comment]
@piyush94 can you send me the stack trace for the first error `Runtime error: Select for update failed Unhandled exception: Failed to finish audit recording`. 

It looks like the certs are not installed correctly.  How are you getting modified jssecacerts  updated into the jre directory?  BTW, none of the code around the sync of issues has changed.

**Comment by piyush94** [comment]
@sbtaylor15 From our side issue was due to two deployhub instances writing to same host pgsql folder.
This can be a issue right? It kind of corrupted the database copy. Luckily we had a backup and after restoring it the issue is gone.

There was no stack trace for ```Runtime error: Select for update failed Unhandled exception: Failed to finish audit recording```
Thanks.

**Comment by sbtaylor15** [comment]
@piyush94 Yes, the 2 instances of the postgres server (from the docker containers) accessing the same data files would cause issues/ corruption.  

So, is the certificate issue now resolved?

FYI, /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc28.x86_64/jre/lib/security is the directory for the jssecacerts base on the JAVA_HOME being used by the jre.

**Comment by piyush94** [comment]
@sbtaylor15 Yes, issue is resolved now. We are putting jssecacerts at this location only.

Thanks.

**Comment by sbtaylor15** [comment]
@piyush94 I added the targetdir update for the component item.  So pull the latest image.  I did not get a chance to test it yet.  I also updated the JenkinsfileMulti example

**Comment by piyush94** [comment]
@sbtaylor15 Is there a recommended way to add certificates to jssecacerts? We are using keytool to add certificates.
Thanks.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - keytool is the only way that I know of.  I believe that you can copy the jssecacerts from another machine if that helps.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Hi Steve, any updates on updating component version while creating new application version?

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we put that in a while ago, but I am not seeing the GitHub comments.  Here it is again:

Please pull the latest image.

https://github.com/DeployHubProject/Uptime-Jenkins-Pipeline/blob/master/JenkinsfileMulti

At the bottom is where we add the component version to the application version.

```
      echo "New Application " + data.toString();
      appid = data[0];

      if (appid > 0 && compid > 0)
      {
       def parent_compid = 0;
       def xpos = 100;
       def ypos = 100;
	  
      data = dh.assignComp2App(url, user, pw, appid, compid, parent_compid, xpos, ypos);
     }    
```

_Note: the ypos needs to be incremented if you are adding multiple component versions to the application version otherwise they will be placed on top of each other._

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 I was asking about, as we had discussed, when creating new application version, it will inherit the component versions from the latest version. And then there should be a way to replace the older component version with the new version from the Jenkinsfile.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 yes, the new application version will inherit from its parent version the components.  Let me check on how the replace is working at the component level.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 do you know the old component version name?  We will need that to make sure we replace the right component.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 old component version might not be known as version is auto-generated during the build.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 do we know part of the name of the component that we can use to do a search?  For example,  foo;v1 is the component in the application version and we need to update it with foo;v2.  We can split on the ; and find the old version based on 'foo'.   Let me know what your naming convention is that you are using for the component version names.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 I think we have a way to do this with relying on a naming standard.  The new component version and the existing component version will both be derived from the same base component version.  We are going to make the component version add to the application version look for an existing component to replace and if that is not found then add it as the last component in the list.  This should simplify what is needed for code in the Jenkinsfile.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 we are following naming convention as comp;x.y.z-a and comp;x.y.z-b, to comply with SemVer v2 version naming system. It would be good to replace the previous component version with new component version from the Jenkinsfile.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we changed the code to find the component version that is derived from the same base as the component being added to the application version.  If found a replace will happen.  If not found it will be added.

Here is a sample Jenkinsfile:

```
 // create component version
      compid = dh.newComponentVersion(url, user, pw, comp, "", version);
      echo "Creation Done " + compid.toString();

      // update attrs
      def attrs = [
	     buildnumber: env.BUILD_ID,
	     ComponentType: "Helm Chart",
	     Category: "Deploy",
	     AlwaysDeploy: "Y",
	     DeploySequentially: "Y",
	     'creds["helmrepo"]': "ec2user",
	     Chart: "stable/heartbeat",
	     ChartVersion: "1.0.0",
	     ChartNamespace: "dev1",
	     'image.tag': "1.0.0"
	    ];
	    
      echo "${attrs}";
      data = dh.updateComponentAttrs(url, user, pw, comp, "", version , attrs);
      echo "Update Done " + data.toString();

      // Create new application version
      data = dh.newApplication(url, user, pw,application,appver, envs);
      echo "New Application " + data.toString();
      appid = data[0];
	  
      // Add new component version to application version
      data = dh.addCompVer2AppVer(url, user, pw, appid, compid); 
```

Please pull latest image for master and beta.  The groovy library in our git repo has been already updated.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Component version replace is not happening. Kindly look into this.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Also in Timeline it doesn't reflect when the component is being added/removed by groovy script.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please upload a screen shot of the base component versions tab that shows how the component versions are linked together.  And then upload a screen shot of components associated to the application version.  Let me know which component version is messed up.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 All the component versions were created using groovy.
![image](https://user-images.githubusercontent.com/11614204/68917565-dea10100-0790-11ea-940a-9b4cb6d7561c.png)

Application has only one component version associated with from the above base component. Also added using groovy.
But when i do the next build in Jenkins component version is not getting replaced.
![image](https://user-images.githubusercontent.com/11614204/68917625-2d4e9b00-0791-11ea-9066-523b64d43450.png)

I think error is not due a specific component version. I tried with all of them.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Received email stating that the component replacement is now working with the latest version of the groovy library.

**Comment by piyush94** [comment]
@sbtaylor15 Component item details are not getting replaced from Jenkins groovy.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 is a new component version being created?  Also, are any of the component item details being saved?  Please send the groovy output.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 instead of creating new component version, we are calling
```compid = dh.newComponentVersion(dhurl, user, pw, comp, "", version, "file",component_items);```
with existing version, with component_items having updated item details. Changes are saved if the version doesn't exist. But if exists, it doesn't updates the details and/or attributes.

Groovy output:
![image](https://user-images.githubusercontent.com/11614204/69647228-1d875e80-108f-11ea-80e4-24c1b7f2c3e5.png)

output is same, doesn't shows error.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 the groovy code was only creating new component items for new components.  Updated the groovy to now handle existing components.  Also, fixed the links between new component items.  The git repo for the groovy library is all set.  You will need to pull the latest image since we had to make a server side change to return the component version id back to groovy.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94  - Can we close this issue?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - One additional feature we were hoping is the ability to add/update attributes on objects other than Component, primarily Application, Environment and End-Point. Let us know your input on this.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - Hi, for a failed deployment, we are still getting success in the groovy stage.
![image](https://user-images.githubusercontent.com/11614204/71610233-3961b100-2bb5-11ea-8fd0-f0c2e487919e.png)

![image](https://user-images.githubusercontent.com/11614204/71610240-4bdbea80-2bb5-11ea-9556-0b833d287e55.png)

It should send correct return code and status.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 is the wrong return code coming from the deploy application or get logs call?  Get logs should have the return code from the completed deployment.

**Comment by piyush94** [comment]
@sbtaylor15 - it's from getLogs. Earlier i was looking at deployApplication, but then i tried with getLogs as mentioned in my comment.

**Comment by sbtaylor15** [comment]
@piyush94 looks like the return code is not being parsed out correctly from the getLogs. We will debug what is going on.

**Comment by sbtaylor15** [comment]
@piyush94 the getLogs was returning the success/failure of the API call and not the success/failure of the deployment.  Updated the Groovy code to parse for the correct return code from the API.  The first element in the array will be true/false for the successful completion of the deployment.  The second element in the array will be the logs.  

The changes have been merged on to master for jenkinsci/deployhub-plugin project.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - thanks, It's working now.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we added methods to set attrs on application, environment and end points.  See the groovydoc.  The deployhub groovy master branch is up to date with these changes.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 can we close this issue?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 yes, this issue can be closed.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Is there a way to auto-increment the application version from Jenkins in `newApplication` function?

**Comment by sbtaylor15** [comment]
Yes, what is the naming format that you are using for the Application Version?

**Comment by piyush94** [comment]
@sbtaylor15 we just want to give the application name, application version as an empty string "", so that deployhub can increment version by itself as it does from GUI.
The only conflict is if we don't want to create a new app version and just want to create the base version the current function works fine.
But there should, not sure a new function or changes to the existing function (without changing parameters), that somehow it understands this.
The empty version string can mean either auto-increment version from the latest, or create an app base version.

**Comment by piyush94** [comment]
@sbtaylor15 I tried the function with changes, The version is set to empty.
![image](https://user-images.githubusercontent.com/11614204/91036763-88b58f80-e625-11ea-8fb1-e8fa09e5296e.png)

**Comment by sbtaylor15** [comment]
@piyush94 we have been able to recreate the error.  debugging why the ;1 is missing on the new version

**Comment by piyush94** [comment]
@sbtaylor15 any update on this?

**Comment by sbtaylor15** [comment]
@piyush94 the missing ;1 has been fixed in the latest version.  We are in the process of pushing those changes back to the version that you are running.

**Comment by sbtaylor15** [comment]
@piyush94 we have updated the fix for the ;1 to all versions.  You will still need to use the [updateattrs branch](https://github.com/jenkinsci/deployhub-plugin/tree/updateattrs).  Please pull the latest image

**Comment by piyush94** [comment]
@sbtaylor15 Thanks, version increment is working now.

**Comment by piyush94** [comment]
> ```
> // // update attrs
> def attrs = [
> 	     BuildId: env.BUILD_ID,
> 	     BuildUrl: env.BUILD_URL,
>              Chart: "harbor-lib/"+imagename, 
> 	     chartversion: version,
> 	     operator: "Kubernetes operator",
> 	     DockerBuildDate: "timestamp",
> 	     DockerSha: "sha for the docker image",
> 	     DockerRepo: "url for the docker registry",
> 	     GitCommit: "git commit",
> 	     GitRepo: "git repo",
> 	     GitTag: "git tag",
> 	     GitUrl: "git url",
> 	     buildnumber: env.BUILD_ID, 
> 	     buildjob: "GLOBAL.test-project",
> 	     ComponentType: "Wildfly_EP",
> 	     ChangeRequestDS: "GLOBAL.JiraUnisys",
> 	     Category: "General",
> 	     AlwaysDeploy: "N",
> 	     DeploySequentially: "N",
> 	     BaseDirectory: "tmp",
> 	     PreAction: "GLOBAL.Run_SQL_Script_Postgres",
> 	     PostAction: "GLOBAL.Run_SQL_Script_Postgres",
> 	     CustomAction: "GLOBAL.Run_SQL_Script_Postgres",
> 	     Summary: "Pipeline Comp"
> 	    ];
> echo "${attrs}";
> // // def updateComponentAttrs(String url, String userid, String pw, String compname, String compvariant, String compversion, Map Attrs)
> data = dh.updateComponentAttrs(url, user, pw, comp, "", version , attrs);
> ```

Hi @sbtaylor15, Could you please provide the available attribute names for applicaiton that can be updated from jenkins?

**Comment by sbtaylor15** [comment]
@piyush94 we need to add setting the email templates to the API.

**Comment by sbtaylor15** [comment]
@piyush94 - here are the keys names for attrs at the app level

FailureTemplate
SuccessTemplate
CustomAction
PostAction
PreAction
ChangeRequestDS

The template names are unique so no domain name is needed.

Images - ui-skin-v9.0.0.3095-g8d2853c (new ui) and master-v9.0.0.2942-gd42f25b (old ui)

**Comment by piyush94** [comment]
@sbtaylor15 Thanks!

**Comment by piyush94** [comment]
Kindly share the key names for endpoint attributes. Not able to update Endpoint Type from updateEndpointAttrs function.

**Comment by sbtaylor15** [comment]
@piyush94 there are no specific key names for endpoints as with components.  So you can define anything that you would like.  Also, I retested the updateEndpointAttrs function and it is working on my end.  Make sure the endpoint exists and that you use the full name, ie "GLOBAL.win10".  Send us the output log if its still failing.

**Comment by piyush94** [comment]
@sbtaylor15 I am able to add endpoint attributes. Only issue is i am not able to update endpoint type. Like we have `ComponentType` attribute for components, is there one for endpoints?

**Comment by sbtaylor15** [comment]
Ah, let me check.  I believe we need to add that for EndPoints.
