### ISSUE TITLE
Attach deployment logs with email notifier

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#257]
Is it possible to attach deployment logs to the notification email template?

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Do you want the logs inlined into the email or as an attachment?

**Comment by piyush94** [comment]
@sbtaylor15 This one's not a priority. Either way would be fine,

**Comment by sbtaylor15** [comment]
Add log text to Body

**Comment by piyush94** [comment]
@sbtaylor15 - Hi, any updates on this. It will be fine if we can add log text to the mail body.

**Comment by sbtaylor15** [comment]
@piyush94 please pull the latest image and use $DEPLOY_LOG in your email template.  We restricted the log size to be 2mb.  Also, it will just email the log data that has been written to the db at the time of invocation. 

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - Thanks, this is working.
But, when i am trying to save the notifier template with a variable in subject, its giving errror.
`/dmadminweb/TemplateDetails?f=seb&id=3&sub=Application%20${application.name}%20failed%20to%20deploy&b=Application%20$%7Bapplication.name%7D%20failed%20to%20deploy%20to%20environment%20$%7Benvironment.name%7D.%0A%0A$%7BDEPLOY_LOG%7D`

`HTTP code 400`

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - let me uri encode the ${application.name} and see if that fixes it.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - We were not able to recreate this issue.  It appears that nginx maybe causing the issue in the way it is handling the $ in the url string.  We encoded the ${application.name} in the url so nginx should pass it through correctly.  Please pull the latest image.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - Thanks it's working now.

CC: @svisagan83
