### ISSUE TITLE
Copy files from windows share location

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#260]
Pulling files from windows share location, without having to mount it as a filesystem.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Right now the windows share has to be mounted to the DeployHub docker container.  

Enhancement is to create a Windows FS repository that will "check out" from the windows share to the drop zone.

**Comment by sbtaylor15** [comment]
Use pre-action at the application to pull files from the windows folder to a location in the docker container.  Then a file system repository will be used push the files to the end points.

**Comment by sbtaylor15** [comment]
@piyush94 Are the files being shared via a Windows Server or another way such as a NAS?  If it is a windows server, will there be WinRM access to it?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 In most cases it's a Windows Server with a shared location. Regarding WinRM, it comes disabled by default, so we have to go and enable it initially. It will have WinRM access after that.
CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 I believe we have a found solution that will work without the need for WinRM and work directly against the windows share.  Testing it out now.

**Comment by sbtaylor15** [comment]
@piyush94 here is the setup.  Please pull the latest docker image then import the procedure into the GLOBAL Functions & Procedures tree. 

[export_RunWinShare.zip](https://github.com/DeployHubProject/DeployHub-Pro/files/3527840/export_RunWinShare.zip)

Next, setup the Action

<img width="464" alt="runwinshare-action" src="https://user-images.githubusercontent.com/14826572/63477386-1b838300-c442-11e9-9511-dc5be5b2a41f.png">
<img width="311" alt="runwinshare-details" src="https://user-images.githubusercontent.com/14826572/63477392-20e0cd80-c442-11e9-9f72-c73917825ff1.png">

Next, setup a Component that uses the Action as a Custom Action.  Make this component the first one in the list of Components for the Application Version.

<img width="596" alt="comp-attrs" src="https://user-images.githubusercontent.com/14826572/63477429-508fd580-c442-11e9-87cf-fc2b27c61b4f.png">

![image](https://user-images.githubusercontent.com/14826572/63477469-787f3900-c442-11e9-948e-c8c98f50d461.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 FYI, no WinRM changes are needed.

**Comment by piyush94** [comment]
@sbtaylor15 I am getting this error:

![image](https://user-images.githubusercontent.com/11614204/63492096-5afbaf00-c4d6-11e9-9c8b-31484cf370f2.png)

![image](https://user-images.githubusercontent.com/11614204/63492109-62bb5380-c4d6-11e9-96a7-1d2fd2e48124.png)

![image](https://user-images.githubusercontent.com/11614204/63492145-74046000-c4d6-11e9-8e85-6a277908b40e.png)

![image](https://user-images.githubusercontent.com/11614204/63492161-7c5c9b00-c4d6-11e9-9d33-093c91e2f792.png)

![image](https://user-images.githubusercontent.com/11614204/63492192-91d1c500-c4d6-11e9-890c-c5da28629388.png)

![image](https://user-images.githubusercontent.com/11614204/63492206-9bf3c380-c4d6-11e9-9c93-5b2f91212b11.png)

I have created a filesystem repo pointing to the winshare_folder, that as per my understating, will be in the deployhub container, and the above action is supposed to mount the windows share at that location.

![image](https://user-images.githubusercontent.com/11614204/63492358-f1c86b80-c4d6-11e9-842f-4b36e710af9c.png)

Let me know if i am missing something.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 make sure your WriteEnv2File procedure has the following code at the start.  Replace what is there in your proc with this.

```
  set -g RspFile = ${dropzone.path} + "/env.dat";
     
    set sname = ${component.name.regsub("[-.; ]","_")};

    eval("using stream \$$sname;");
    eval("set envstream = \$$sname;");
     
    using stream $envstream {
```

For the file system repo - set it up as `file path = /winshares` and mark it as `appendable`.  
For the mount component item attrs set the `winshare_folder = share` and `winshare_sharename = \\USTR-UVM-12271\c$`

The files will end up in the container as `/winshares/USTR-UVM-12271/c$/share/site.zip` so set the IIS component item `file path = USTR-UVM-12271/c$/share`  and `pattern = site.zip`

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Did the above changes but still same error.
![image](https://user-images.githubusercontent.com/11614204/63569906-dde53e00-c598-11e9-86f9-b91dad4959d6.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
How is the Action setup to run? Pre action to the application or a custom action for a component?

**Comment by piyush94** [comment]
Pre action to application.

**Comment by piyush94** [comment]
> @piyush94 - ok, the component.name is undefined at that level. Change the WriteEnv2File as follows:
> 
> ```
>   set -g RspFile = ${dropzone.path} + "/env.dat";
>     set d = now();
>     set sname = "s" + ${d.to_int()};
> 
>     eval("using stream \$$sname;");
>     eval("set envstream = \$$sname;");
> ```

Will this affect ansible playbook action at component level?

**Comment by piyush94** [comment]
@sbtaylor15 above issue is gone, but a new issue is happening.
1. I created a new application version from base version to try this feature.
2. I assigned the environment to the new version as i guess it doesn't inherits environments assigned to base version.
3. When i am deploying the assigned environments list goes empty and i get this error:
```
INFO: Starting deployment #265
--
INFO: Deploying Application "Deploy_IIS_Site;1" into Environment "IIS_Env"
Deploying  to
Syntax error at line 37 of "action WriteEnv2File": Invalid type for for loop - must be string, array or stream
INFO: Time taken 0.011769 seconds
```

write2env at line 37:
```
foreach(env: ${server.attributes}) {  
      echo $env + ": " + ${server.attributes[$env]};
    }
```

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 This one worked to some extent. I was getting the below error:
![image](https://user-images.githubusercontent.com/11614204/63827832-309c6c80-c982-11e9-838c-fed086bdad31.png)

Turns out in our case the access to winshares is controlled by Active Directory and we also need to pass the user domain also.
ref: https://askubuntu.com/questions/109507/smbclient-getting-nt-status-logon-failure-connecting-to-windows-box

So, i changed the dh2winshare script to accept a user domain variable and it was able to mount the share, but it failed to copy files from the path.
![image](https://user-images.githubusercontent.com/11614204/63828429-05b31800-c984-11e9-969e-1f002a7e1179.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 script changes:
```
@click.option('--winshare_userdom', help='User domain', required=True)

def main(winshare_user, winshare_pass, winshare_sharename, winshare_folder, winshare_userdom):
    """Main entry point"""

    user = winshare_userdom + "/" + winshare_user + "%" + winshare_pass
```

CC: @svisagan83

**Comment by piyush94** [comment]
INFO: Starting Sequential Deployment of Component IIS_Test_Site;1
--
INFO: Removing Component IIS_Test_Site from Server inblr-uvm-1118
PLAY [Execute File] ************************************************************
TASK [Execute File] ************************************************************
fatal: [inblr-uvm-1118.eu.uis.unisys.com]: FAILED! => {"changed": false, "cmd": "-dellist /tmp/tdm.8589.1.tmp", "msg": "Exception calling \"SearchPath\" with \"1\" argument(s): \"Could not locate the following executable -dellist.exe\"", "rc": 2}
to retry, use: --limit @/tmp/tmpabbx7vna/runit.retry
PLAY RECAP *********************************************************************
inblr-uvm-1118.eu.uis.unisys.com : ok=0    changed=0    unreachable=0    failed=1

**Comment by sbtaylor15** [comment]
@piyush94 - added the user domain code and resolved the -dellist parameter error.
Please pull latest image

CC: @svisagan83
