### ISSUE TITLE
Stop deployment on component error

### ISSUE THREAD

**Issue by sbtaylor15** [DeployHubProject/DeployHub-Pro#265]
Bad return code from function stops action for a component but next component  still proceeds.  Need to stop all components.

**Comment by sbtaylor15** [comment]
@piyush94 change to throw an error when zero files are checked out of a repo and when the remote script returns a non-zero return code.  Let me know if there are any other use cases you would like to see the deployment stopped.

Please pull latest image.


docker pull quay.io/deployhub/deployhub-pro@sha256:63806aa8b0d586f2518a291756b19f5ae7b84cfa1dcf3af3140fcf0b0e5d71cc

**Comment by sbtaylor15** [comment]
CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 working now.

CC: @svisagan83
