### ISSUE TITLE
execute permission issue on bash scripts

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#266]
@sbtaylor15 This issue is still occuring.
```
PLAY [Execute File] ************************************************************

TASK [/tmp/harbor-install.sh ustr-uvm-15078.na.uis.unisys.com ustr-uvm-14870.na.uis.unisys.com Unisys*1234] ***
fatal: [ustr-uvm-15078.na.uis.unisys.com]: FAILED! => {"changed": false, "cmd": "/tmp/harbor-install.sh ustr-uvm-15078.na.uis.unisys.com ustr-uvm-14870.na.uis.unisys.com Unisys*1234", "delta": "0:00:00.004102", "end": "2019-08-06 08:24:09.883367", "msg": "non-zero return code", "rc": 126, "start": "2019-08-06 08:24:09.879265", "stderr": "/bin/sh: 1: /tmp/harbor-install.sh: Permission denied", "stderr_lines": ["/bin/sh: 1: /tmp/harbor-install.sh: Permission denied"], "stdout": "", "stdout_lines": []}
 to retry, use: --limit @/tmp/tmpk3s871t7/runit.retry

PLAY RECAP *********************************************************************
ustr-uvm-15078.na.uis.unisys.com : ok=0    changed=0    unreachable=0    failed=1   
```

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 is the /tmp/harbor-install.sh already existing on the remote server.  Or is the procedure setup with "Copy to Remote"?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 file is getting copied from a repository to the endpoint.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 can you let us know what the permissions of /tmp/harbor-install.sh are on the remote server?  Thx

**Comment by piyush94** [comment]
```-rw-r--r-- 1 root root 3807 Aug  6 08:24 harbor-install.sh```

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 Added chmod 0755 for files that are already on the end point or setup as "Copy to Remote"

CC: @svisagan83

docker pull quay.io/deployhub/deployhub-pro@sha256:63806aa8b0d586f2518a291756b19f5ae7b84cfa1dcf3af3140fcf0b0e5d71cc

**Comment by piyush94** [comment]
@sbtaylor15 working now.

CC: @svisagan83
