### ISSUE TITLE
docker container item not deploying

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#267]
![image](https://user-images.githubusercontent.com/11614204/62854256-67c91780-bd0c-11e9-956b-7c7108217e05.png)

![image](https://user-images.githubusercontent.com/11614204/62854271-79aaba80-bd0c-11e9-8417-f7da9eae96bc.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 And also there should be a option to specify K8 namespace for the helm chart.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
- helm init client only
- run helm on remote cluster
- namespace flag on helm install

working when attrs are assigned at component level

**Comment by sbtaylor15** [comment]
Add Release Name as variable for helm upgrade parameters.

**Comment by sbtaylor15** [comment]
@piyush94 here is the update WriteEnv2File and WriteEnv2Toml procedures.  Please import these into GLOBAL domain.  The import will overwrite the existing procedures.  

[WriteEnvProc.zip](https://github.com/DeployHubProject/DeployHub-Pro/files/3564279/WriteEnvProc.zip)

The dh2helm.py will look for the creds['helmrepo'] variable to pull the credentials for the helm repo login.

Also, the helm deployment will now run on the remote server or localhost (the DH docker container).

Namespace is now part of the Docker Component Item.

Both dh2ansible.py and dh2helm.py were updated to handle using ssh key file if the credential is setup as a Private Key type.

We have regression tested the IIS deployment using the WinShare and IIS playbook.  And tested helm deployments locally and remote.  

Please pull the latest image. 

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Add helmopts to pass in additional cmd line parameters

**Comment by piyush94** [comment]
@sbtaylor15 Little urgent issue, the writeenvtoml is not writing Chart attribute from docker container item and as a result dh2helm is not picking up the Chart attribute,

![image](https://user-images.githubusercontent.com/11614204/64674171-b2fe5380-d48d-11e9-9c11-a0107376d185.png)

I tried by adding Chart attribute in application and it worked.
![image](https://user-images.githubusercontent.com/11614204/64674210-cf01f500-d48d-11e9-9d75-4fcc0bddbbb0.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Also releasename should only be the component name, but it's combining component name, version and chartname for releasename.

![image](https://user-images.githubusercontent.com/11614204/64674308-230cd980-d48e-11e9-9dab-24419222a222.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 creds["helmrepo"] is not getting picked up.
![image](https://user-images.githubusercontent.com/11614204/64689830-bce37f00-d4ac-11e9-9e0d-b2d51e4339a3.png)

![image](https://user-images.githubusercontent.com/11614204/64689900-d97fb700-d4ac-11e9-945b-2c36f016046e.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 can you send a screen shot of the docker component item and of the attributes on the component.  I need to see the values listed there, specifically the chart name.  I want to make sure the chart name is getting saved to the database for the component item.  Also, the chart at the component attribute maybe being overridden by the docker component item.

**Comment by piyush94** [comment]
@sbtaylor15 correct attributes in Jenkinsfile screenshot:
![image](https://user-images.githubusercontent.com/11614204/64713127-fa123600-d4d9-11e9-9f72-ab2a75fee480.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - please pull latest image that fixes the password from being displayed

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Hi, any update on helmopts to pass additional arguments. This is required because we have multiple deployment clusters and we need to set --kubeconfig flag with relevant config file while deploying to a particular cluster.
Thanks.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please pull the latest image.  set helmopts attribute to any string and it will be added to the helm upgrade command line after the namespace parameter.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Hi Steve, i am trying to override the chartnamespace at environment level. but i am getting the below error.
![image](https://user-images.githubusercontent.com/11614204/67192433-373ee180-f411-11e9-99d9-bf8a14696f37.png)

![image](https://user-images.githubusercontent.com/11614204/67192503-550c4680-f411-11e9-90eb-5472cf8b0935.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please pull the latest image.  Changed the dh2helm.py to enable overriding of the variables.  

Override order is as follows:
- Environment
- Application
- Server
- Component

For example, variable 'foo' at the component level will override 'foo' defined at the environment level.

FYI, these changes have been made to the beta branch as well.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 our use case was to override the variable at component level with variable at environment level. The thing is we wouldn't want to change namespace for each component instead override it with what is available at environment level. Could you please suggest a better solution/workaround for this use case?
Thanks,

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 if you just want to reverse precedence we can do that in the WriteEnv2Toml procedure.  But if you want to have an override at any point in the precedence hierarchy we will need to come up with another solution.  Let me know which way you want to go.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 precedence order is fine for now. One issue happening is we are not able to leave chartnamepspace empty at component level. We have defined chartnamespace at environment level but it's taking value "0" instead taking from environment.

Log:
![image](https://user-images.githubusercontent.com/11614204/68740060-3b28e280-0610-11ea-974e-643f49aabe99.png)

Component Item:
![image](https://user-images.githubusercontent.com/11614204/68740111-55fb5700-0610-11ea-955e-1a9844cd6071.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 chartnamespace was provided at application level but it still got set to "0".
![image](https://user-images.githubusercontent.com/11614204/68784791-245fab80-0663-11ea-9326-bab717ef3811.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we fixed the code to handle chartnamespace being blank.  Please pull the latest image.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94  - Can we close this issue?

CC: @svisagan83
