### ISSUE TITLE
Add horizontal scroll to Component Hub in application view

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#269]
Currently if there are nested subdomains, the component names are getting clipped from the view.
![image](https://user-images.githubusercontent.com/11614204/64010573-aa298b80-cb37-11e9-8e4b-8efe3dc7a83c.png)

**Comment by sbtaylor15** [comment]
@piyush94 we added horizontal scroll bars on all tree view. BTW, the new UI design is phasing out the tree views.  Please pull the latest image.

CC: @svisagan83
