### ISSUE TITLE
Query: windows endpoint port

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#270]
In windows endpoint connection with WinRM, is deployhub using port 5985 which is unencrypted or port 5986 which is encrypted?

**Comment by sbtaylor15** [comment]
The default port is the encrypted default port of 5986.  Also, we use CredSSP and TLS 1.2 which are both encrypted.

**Comment by piyush94** [comment]
Thanks

**Comment by piyush94** [comment]
@sbtaylor15 I tried connecting to an Azure VM from deployhub and it is trying to connect over HTTP 5985 which is not allowed by our firewall policy.

![image](https://user-images.githubusercontent.com/11614204/65592500-50887580-dfac-11e9-9d45-0d813d3c55c3.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we removed the code to switch between http and https.  Now letting ansible handle this for us.  Please pull latest image.

CC: @svisagan83
