### ISSUE TITLE
Jenkins credentials inside groovy pipeline script

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#272]
Way to use Jenkins credentials inside groovy pipeline script for deployhub library.

CC: @svisagan83

**Comment by piyush94** [comment]
Reference: https://jenkins.io/doc/book/using/using-credentials/

**Comment by sbtaylor15** [comment]
@piyush94 

First add the environment to the top of your pipeline as follows:

```
@Library('deployhub') _

environment {
    DEPLOYHUB_CREDS = credentials('deployhub-creds')
}

def app="ChiliUptimeApp"
def environment=""
def cmd=""
def url="http://voltron:7171"
def user=env.DEPLOYHUB_CREDS_USR
def pw=env.DEPLOYHUB_CREDS_PSW

def dh = new deployhub();
```

Create the Jenkins Credentials `id=deployhub-creds` as plain userid/password.

See https://jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Thanks, it's working.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Will users be able to echo the password variable?

**Comment by piyush94** [comment]
@sbtaylor15 The above fix was not working:
![image](https://user-images.githubusercontent.com/11614204/64849365-e0373700-d630-11e9-8ec7-e88b659b5c43.png)
![image](https://user-images.githubusercontent.com/11614204/64849413-f218da00-d630-11e9-92f0-f267305305e6.png)

I replaced it with below:
```
 if (userid.indexOf('@') == 0)
   {
    def cred = userid.substring(1);
      def creds = com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(
  com.cloudbees.plugins.credentials.common.StandardUsernameCredentials.class, Jenkins.instance, null, null ).find{
    it.id == cred};
    def username = creds.username;
    def password = creds.password;
     URL url = new URL(requestUrl);
     HttpURLConnection connection = url.openConnection();

     connection.setRequestMethod(verb);
     connection.setRequestProperty("Content-Type", "application/json");
     connection.setRequestProperty("Cookie", "p1=$username; p2=$password");
```

It started working.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Hi @piyush94, thanks for digging up at alternative way of getting the credentials.  Did we hide it well enough from the end user?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Yes, i think it's good enough for now. Thanks.

CC: @svisagan83
