### ISSUE TITLE
Docker component item not getting inherited

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#276]
Docker component item is not getting inherited after creating new component version.
It reverts to simple component item and losing details associated with docker component item.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 what are you using to create the new component version, Jenkins or the DeployHub UI?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 deployhub UI.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please pull the latest image for the fix.  The UI was always using the base version to copy from instead of the latest version.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 fixed.

CC: @svisagan83
