### ISSUE TITLE
Components not visible in the Component Hub

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#278]
Components are not visible for a subdomain if it's not having any child subdomains.

**Comment by sbtaylor15** [comment]
@piyush94 can you send a screen shot of your domain structure?

**Comment by piyush94** [comment]
@sbtaylor15 I had to create a DummyDomain for the treeview to be expandable in the component hub to access components.
![image](https://user-images.githubusercontent.com/11614204/68692454-8b199200-059b-11ea-863a-e98c21e5b42b.png)

![image](https://user-images.githubusercontent.com/11614204/68692526-a7b5ca00-059b-11ea-8ff9-f40782751199.png)
Sec

**Comment by piyush94** [comment]
This issue is not happening if the user is part of GLOBAL domain.

**Comment by sbtaylor15** [comment]
@piyush94 - that explains why I can't recreate it.  Let me change users and debug the issue.

**Comment by sbtaylor15** [comment]
@piyush94 - please pull latest image for fix.

**Comment by piyush94** [comment]
@sbtaylor15 Thanks. Components are now visible.

CC: @svisagan83
