### ISSUE TITLE
Bind task parameters to object attributes

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#279]
Is it possible to bind task parameters to object (component, application, etc.) attributes?
example scenario:

Parameter:
![image](https://user-images.githubusercontent.com/11614204/68691357-a1bee980-0599-11ea-8099-4c994a4f6465.png)

Component:
![image](https://user-images.githubusercontent.com/11614204/68691442-be5b2180-0599-11ea-9cbf-5b6d7f43fa28.png)

Deploy Task:
![image](https://user-images.githubusercontent.com/11614204/68691503-db8ff000-0599-11ea-906e-dca9ba8f8008.png)

Log:
![image](https://user-images.githubusercontent.com/11614204/68691545-f1051a00-0599-11ea-8e77-28fd82b5655c.png)

CC: @svisagan83

**Comment by piyush94** [comment]
This would be helpful to template the component and fill in the required values at run-time.

CC: @svisagan83

**Comment by piyush94** [comment]
Other way would be to define attributes at application level and access them at component level.
Example:
Application:
![image](https://user-images.githubusercontent.com/11614204/68692723-f5323700-059b-11ea-9dbd-ac7dc07d6612.png)

Component:
![image](https://user-images.githubusercontent.com/11614204/68692766-09763400-059c-11ea-88cb-e856c6a5dafb.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Also let us know if there is a way to achieve the above task in the current version of DeployHub. Thanks.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 the change has been included in the latest release.  No changes needed to your pre-post actions.  The deployment engine will expose these for you.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 it was working with environment and endpoint also earlier, but now it is only working with application. Kindly look into this.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please send a screen shot of how you are defining the variables at the environment and end point.  

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 
**Environment**
![image](https://user-images.githubusercontent.com/11614204/69647371-60493680-108f-11ea-8f5b-51a46279a4dd.png)

**Endpoint**
![image](https://user-images.githubusercontent.com/11614204/69647403-6d662580-108f-11ea-806c-564951091ed1.png)

Also this warning is coming:
![image](https://user-images.githubusercontent.com/11614204/69647492-9981a680-108f-11ea-9d23-f8f7090db83a.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 log where we can see attributes not getting resolved:

- 'EXT: sh'
  - 'RE_PHYSICAL_HOSTNAME: <hostname>'
  - 'RE_PHYSICAL_SERVER: small-dev-1-hlf-org1'
  - 'application: hlf-network;0_1_0'
  **'caKeyFileName: $ca_keyfilename'
  'ca_keyfilename: 52185a3f9a660e8a4d54397238370ba82f19969decdd5d4ceec541b9553b5629_sk'**
  **'ca_postgres_enabled: ''true'''**
  **'ca_relname: ca-org1'**
  - 'ca_secret_serverconfig: ca--ca-server-config'
  - 'chart: main/hlf-ca'
  **'chartnamespace: $kube_namespace'** // not getting resolved at component level
  - 'chartversion: 1.4.1-94'
  - 'cli_relname: cli-org1'
  - 'cli_secret_admincerts: cli--admin'
  - 'cli_secret_cacerts: cli--ca'
  - 'cli_secret_keys: cli-pub'
  - 'cli_secret_keystore: cli--keystore'
  - 'cli_secret_signcerts: cli--signcerts'
  - 'cli_secret_tls: cli-tls'
  - 'cli_secret_tlscacerts: cli--catls'
  - 'client_tls_enabled: ''false'''
  - 'component: ca;1_4_1_105'
  - 'config:'
  - '  affiliations:'
  - '    org1: ''{department1}'''
  - 'dropzone: /tmp/tdm.942.1'
  - 'environment: small-dev-1'
  - 'fullnameOverride: ca'
  - 'helmopts: --kubeconfig ~/small-dev-1/config'
  - 'helmrepo:'
  - '  name: main'
  - '  url: <url>'
  **'kube_namespace: hlf-org1'** // defined at environment level
  - 'peer_org_mspid: org1'
  - 'peer_relname: peer-org1'
  - 'persistence:'
  - '  storageClass: nfs-client'
  - 'postgresql:'
  **'  enabled: ${ca_postgres_enabled}'**
  **'relname: $ca_relname'**
  - 'secrets:'
  - '  caServerConfig: ${ca_secret_serverconfig}'
  - 'server_hostname: USTR-UVM-19324.na.uis.unisys.com'
  - 'server_name: small-dev-1-hlf-org1'
  - 'server_tls_enabled: ''true'''

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - we move some of the code around that does the variable resolution and tested several different  locations of the variables.  From our testing all of the variables are now resolving as expected.  Please pull the latest image and see how the variables resolve with your data.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 The attribute values seem to be resolving but not getting reset for the second environment:
![image](https://user-images.githubusercontent.com/11614204/70333326-4e267f80-1869-11ea-9271-c6b5d803efd9.png)

![image](https://user-images.githubusercontent.com/11614204/70333545-b1b0ad00-1869-11ea-8edc-01fd78c5c8c2.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 -we updated the code to return a new instance of the expanded variable instead of reusing the same instance.  The change passed our test cases.  Please pull down the latest image and let us know if the variable is expanded correctly with your variable configuration.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - it seems the resolution itself is not working now.
![image](https://user-images.githubusercontent.com/11614204/70445298-4d882600-1ac1-11ea-95af-e420e52eea77.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please pull the latest image and give it try again.  We made one small change that we believe will work with your data configuration.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - above issue is fixed now. One more thing is, we are providing releasename as a new variable which again will be resolved depending on the environment or endpoint. The resolved value is correct but it is not being passed to the script.
![image](https://user-images.githubusercontent.com/11614204/70468137-8db0ce00-1aec-11ea-843d-5105552a1414.png)

![image](https://user-images.githubusercontent.com/11614204/70468197-a9b46f80-1aec-11ea-9836-3a549192d486.png)

![image](https://user-images.githubusercontent.com/11614204/70468221-b933b880-1aec-11ea-8236-fb276ae081a0.png)

![image](https://user-images.githubusercontent.com/11614204/70468298-da94a480-1aec-11ea-81b4-2a590a003836.png)

![image](https://user-images.githubusercontent.com/11614204/70468329-e84a2a00-1aec-11ea-9d66-307aad9ee4ff.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - can you change the Helm Upgrade, Release Name parameter from ${relname} to ${hw-relname} to see if it gets resolved correctly?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - it didn't work with the variable name as "hw-relname", so i changed it to "hwRelname" and that worked. But "relname" is not working.
**hw-relname**
![image](https://user-images.githubusercontent.com/11614204/70497753-35a0b880-1b3a-11ea-8b95-31ef59cbed11.png)

**hwRelname**
![image](https://user-images.githubusercontent.com/11614204/70497774-4bae7900-1b3a-11ea-99d5-71ef1c6fe940.png)

**relname**
![image](https://user-images.githubusercontent.com/11614204/70497790-5cf78580-1b3a-11ea-8fe4-da10172fb717.png)

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - will it be possible to achieve the attribute resolution, the way i have specified?
Regards.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we are in the process of determining the best way to handle the variable expansion for the parameters.  The parameters are handled differently than regular variables.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - we changed the expansion routine to a recursive lookup.  The scenario you described passed our testing.  Please pull the latest image.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - the attributes are now resolving, only issue is that at helm install level it's not working.
```- 'ca_relname: ca-hlf-org1'```

```- 'relname: ca-hlf-org1'```

![image](https://user-images.githubusercontent.com/11614204/71353721-ee85df00-259f-11ea-96e5-508a31eb44dd.png)

```helm upgrade "${ca-relname}" "main/hlf-ca" --version "1.4.1-117" --namespace "hlf-org1" --kubeconfig ~/small-dev-1/config --set config.affiliations.hlf-org1={department1},config.affiliations.hlf-org2={department1} --install --force --debug -f override/main/hlf-ca/values.yaml```

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - Change ${ca-relname} to ${ca_relname}.  You have a mismatch.

**Comment by piyush94** [comment]
@sbtaylor15 - This is being done by the helm upgrade script.
![image](https://user-images.githubusercontent.com/11614204/71395324-8553a980-263b-11ea-94fe-8678ee85d0ab.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - it looks like the ${ca_relname} name should be expand to ca-hlf-org1 prior to the helm upgrade command is being executed.  Can we do a web meeting to look at this?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - can we have a meeting tomorrow (Friday 1/3/20)?

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we were able to track down where the variable was not being expanded.  Please pull the latest image for the fix.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - release name is getting truncated at “-“ character. 
![091BA17A-088C-41C9-91D8-8FAB3C58EE88](https://user-images.githubusercontent.com/11614204/71847786-dd86b300-30f3-11ea-8162-c96ceade7932.jpeg)
![71795F03-E3E5-4C92-99D6-3810B78A9D07](https://user-images.githubusercontent.com/11614204/71847787-dd86b300-30f3-11ea-86d7-b8f18b682cb5.jpeg)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 the shortened name is only for display and not effecting the actual command being run.  We changed it so more of the helm command line is shown.

Please pull the latest image.  Also, we changed the filtering pick list only to show you what visible in the table not everything.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 can we close this issue?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - closing this issue.

CC: @svisagan83
