### ISSUE TITLE
Objects not saving after new update

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#281]
Objects are not saving after the new update for the deployhub latest tag
![object-save-error-2](https://user-images.githubusercontent.com/11614204/69040624-1b305f00-0a14-11ea-8a17-613f36b6d9ac.JPG)
![object-save-error](https://user-images.githubusercontent.com/11614204/69040628-1cfa2280-0a14-11ea-93e6-31b80d393848.JPG)
 
We tried with multiple objects such endpoint, credentials, etc.
For Component this is coming:
![image](https://user-images.githubusercontent.com/11614204/69041027-d22cda80-0a14-11ea-9fd2-96977ef3c731.png)
 
Kindly look into this on priority.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please pull the latest image.  The following objects had problems:

- End Points
- Notifier Templates
- Credentials
- Deployment Engine

We could not recreate any issues with components or component items.

CC: @svisagan83

**Comment by svisagan83** [comment]
A component created from the Jenkins Build is not visible for the users who are part of that domain. only global administrators can able to view them

**Comment by sbtaylor15** [comment]
@piyush94 can you send a screen shot of the component detail showing the domain information and the access permissions?

cc: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 
**component**:
![image](https://user-images.githubusercontent.com/11614204/69155022-054f9680-0b07-11ea-928d-eb7d331d791d.png)

![image](https://user-images.githubusercontent.com/11614204/69155091-1c8e8400-0b07-11ea-8c47-1498d7e99e17.png)

**domain**:
![image](https://user-images.githubusercontent.com/11614204/69155135-2ca66380-0b07-11ea-857b-f906aa8c1fa2.png)

![image](https://user-images.githubusercontent.com/11614204/69155216-4f387c80-0b07-11ea-9259-8ba9d7604b30.png)

cc: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 does creating a component at the same level as the missing one via the UI enable it to be visible to the non-global users?  Trying to figure out which side the problem is stemming from, Jenkins or access control.

cc: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 rights don't seem to be working correctly. I am not able to create components from the UI even though i have access.

cc: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 what is the group membership for the userid that you are using?

cc: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 it’s in the StealthID-service-group with creation rights for components, applications and application versions.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 does adding the user to the administrators group fix the issue?  This is just a test for debugging.

**Comment by sbtaylor15** [comment]
Changed the domain level check to verify that the component domain matched the users domains.
