### ISSUE TITLE
Unable to navigate to next page in the table view

### ISSUE THREAD

**Issue by svisagan83** [DeployHubProject/DeployHub-Pro#282]
In the new UI, we are not able to navigate to next page on the table view especially when we have more data. The Chat icon is blocking the UI. Also, it would be good if there a filter added to the table. 

![image](https://user-images.githubusercontent.com/19646628/69118653-3655aa00-0aba-11ea-8755-c54f664ac48e.png)

**Comment by sbtaylor15** [comment]
@svisagan83 we will remove the chat icon.  Also, we are in the process of adding a filtering to the table.

**Comment by sbtaylor15** [comment]
@svisagan83 please pull the latest image.  We removed the chat icon.

cc: @piyush94
