### ISSUE TITLE
How to get raw file from BitBucket (Git) from branch other than master?

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#284]
How to get raw file from BitBucket (Git) from branch other than master?

CC: @svisagan83

**Comment by piyush94** [comment]
Or what is the recommended way to get files from git repos as component item?

**Comment by piyush94** [comment]
@sbtaylor15 we were trying to give querystring ?at=refs/heads/<branch_name> , but the ? and / characters are getting url encoded and get request is failing while deploying. 

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 where are you specifying the query string?  At the component item level or as part of the repository definition?

**Comment by piyush94** [comment]
@sbtaylor15 at component item level
![image](https://user-images.githubusercontent.com/11614204/69647914-5542d600-1090-11ea-8260-0e58ee7c49a1.png)

log:
![image](https://user-images.githubusercontent.com/11614204/69647981-70ade100-1090-11ea-90cd-575b08ff5e89.png)

"?" is getting changed to "%3f"

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 let me know if we can give query string at repository definition. It's a http repository (git raw).

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we removed encoding of the ?.  Please pull the latest image.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 the file was trying to be saved to the file system with the query string as part of the name.  We stripped off the query string on the name and its now working as expected.  Please pull the latest image.

CC: @svisagan83
