### ISSUE TITLE
Adding new components to an application via Jenkins does not order them

### ISSUE THREAD

**Issue by bglee** [DeployHubProject/DeployHub-Pro#289]
When adding multiple new components to an application the components do not end up in the correct deployment order. Instead they are all under the base:
![Capture](https://user-images.githubusercontent.com/15132953/72174621-c23fd000-339f-11ea-9cf8-cde37124241d.PNG)

![Capture](https://user-images.githubusercontent.com/15132953/72174029-69bc0300-339e-11ea-8e1c-f90056aacadf.PNG)

This means when I do deployment it freezes and never completes the deployment. (I am not sure why it does this) 

If I rearrange them manually they deploy correctly:
![Capture](https://user-images.githubusercontent.com/15132953/72174779-1fd41c80-33a0-11ea-91e9-608b88282865.PNG)

This works for now but it would be desirable to have the components arranged correctly for sequential deployment when starting a new application from scratch via Jenkins. I would also like to understand why the parallel component deployment freezes.  

CC: @piyush94 , @svisagan83

**Comment by sbtaylor15** [comment]
@bglee we double checked that the new component will be added to the end of the list, but you need to start with an ordered list.  Try running the Jenkins Job with the list already ordered and let us know the results.  A new component should be added to the end and an existing component with new version should be updated in place.

CC: @piyush94 , @svisagan83

**Comment by bglee** [comment]
The following were my experiments. Each time in between I order the components manually. The process creates a new application version before adding the new components to it. It adds multiple components before doing a deploy. 

Script: new application version and add 1 component 
![1](https://user-images.githubusercontent.com/15132953/72293722-bcedba00-3619-11ea-9087-630b89c62e97.PNG)

Script: new application version and add 5 components (Moved components for visibility)
![2](https://user-images.githubusercontent.com/15132953/72293727-be1ee700-3619-11ea-908f-07c6bb167004.PNG)

Manual: Reorder
![3](https://user-images.githubusercontent.com/15132953/72293729-bfe8aa80-3619-11ea-8af8-7e9a08cd2158.PNG)

Script: new application version and add 2 components  (Moved components for visibility)
![4](https://user-images.githubusercontent.com/15132953/72293731-c119d780-3619-11ea-983c-5f00822320be.PNG)

Manual: Reorder
![6](https://user-images.githubusercontent.com/15132953/72294190-aac04b80-361a-11ea-83c5-ed0585c32d07.PNG)

Script: new application version and add 3 components  (Moved components for visibility)
![5](https://user-images.githubusercontent.com/15132953/72293734-c24b0480-3619-11ea-938c-18253250d66a.PNG)

It looks like each time the new components are assigned to the application parallel to the last assigned component. 

Is there another way I should order the components? 

CC: @piyush94 , @svisagan83

**Comment by sbtaylor15** [comment]
@bglee it looks like the last component version in the list is not being found correctly.  Let us double check the logic for finding it.  We may need to do a web meeting.  We will let you know.

The other way is to find the new component's parent and then do the assignment.  This is a bit of work since you need to loop through the version array.

CC: @piyush94 , @svisagan83

**Comment by sbtaylor15** [comment]
@bglee we changed the recursive search to find the last component in the list.  Please reorder back to the serial list and try again with the latest DeployHub image.  The new component should be added to the end of the list.

CC: @piyush94 , @svisagan83

**Comment by bglee** [comment]
@sbtaylor15 - I have confirmed the fix works by running a Jenkins job that adds multiple components. The resulting application has the components ordered sequentially. 

CC: @piyush94 , @svisagan83
