### ISSUE TITLE
A way to create Environments and Endpoints from Jenkins plugin

### ISSUE THREAD

**Issue by bglee** [DeployHubProject/DeployHub-Pro#292]
Recently the Jenkins Deployhub plugin was changed to allow the updating of Endpoints and Environments with new attributes. 

It would be nice if the plugin also contained methods for creating Endpoints and Environments. This way entire Environments could be created from Jenkins pipelines. 

CC: @piyush94 , @svisagan83

**Comment by sbtaylor15** [comment]
@bglee what type of userid and password are you using for your end points?  We don't want to put that info in the Jenkinsfile.  A userid and reference to a private key should be safe since the private key is just a reference and not the key itself.

CC: @piyush94 , @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 In most cases a credential would pre-exist in the DeployHub. Will it be possible to only pass in the reference to the credential while creating endpoint in Jenkinsfile?

CC: @bglee , @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 ok, we will assume that the credential pre-exists and then the jenkinsfile will just supply the name of the credential to use.

CC: @bglee , @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 I think we can close this issue.
