### ISSUE TITLE
not able to create components

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#293]
![image](https://user-images.githubusercontent.com/11614204/73636070-f2bb1700-468a-11ea-8116-a04176854738.png)

Tried with all of the component types and different domains.

version: 20200129_1636

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 please pull the latest image for the fix.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - thanks, is working now.

CC: @svisagan83
