### ISSUE TITLE
not able to save credentials in any domain

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#294]
![image](https://user-images.githubusercontent.com/11614204/74439703-b8bff100-4e92-11ea-9d5c-0a7e086a4bf9.png)

CC: @svisagan83

**Comment by piyush94** [comment]
Hi, any update regarding this? We are not able to proceed with the work due to this issue.

**Comment by sbtaylor15** [comment]
@piyush94 what kind of credential are your trying to save,  public/private key or one encrypted in the database?

**Comment by piyush94** [comment]
@sbtaylor15 encrypted in the database. I am able to save in a new DH container, but in both our sandbox and prod container, I'm facing the issue

**Comment by sbtaylor15** [comment]
@piyush94 is the same image being used across new DH container, sandbox and prod?  

Also, we will need a bit more of the log file.  See an example I sent you via email.

**Comment by piyush94** [comment]
@sbtaylor15 I have replied in the mail.

**Comment by sbtaylor15** [comment]
@piyush94 we added code to prevent the autofill of the password, user name and name fields.  Also, we added additional logic on the backend to deal with the autofill as well.  Please pull the latest image.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 can we close this issue?

CC: @svisagan83
