### ISSUE TITLE
Helm3 for reverse proxy

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#295]
Hi, is it possible to have helm3 along with helm2 installed in the reverse proxy container.
Also a copy of dh2helm script that uses helm3 instead of helm2.
May need to remove helm init step as it's not required by helm3.

Or, it would be better if we can choose between v2 or v3 using an attribute, because otherwise we will need to create a new Action.
Thanks.

**Comment by sbtaylor15** [comment]
@piyush94 we have renamed the helm v2 version binary to helm2 and installed helm v3 as helm.  Also, updated the dh2helm.py accordingly.  We will add an attribute or env var check to determine which version to use.

**Comment by piyush94** [comment]
@sbtaylor15 - thanks for the info. Only concern i have is this broke our helm installs in sandbox and i had to rename helm to helm2 in our helm clients.

**Comment by sbtaylor15** [comment]
@piyush94 - ok, I see whats happening.  We were testing everything using the helm installed in the DeployHub container.  It looks like you are using helm on a remote machine that you installed on your own.  What is your plan for your helm installations?  Just have one version of helm or multiple?  Let us know so we can figure out the naming of the helm exe and switching between helm versions.

**Comment by piyush94** [comment]
@sbtaylor15 - We would be okay to use the same installation as yours.
Helm 2.16.x -> helm2
Helm 3.x.x -> helm

I've taken the below commands from the DeployHub container and used them to setup a machine
![image](https://user-images.githubusercontent.com/11614204/76727253-877c5e80-6779-11ea-9066-93ddc37d70fe.png)

I verified on my remote machine to not have any issues with both versions installed and there weren't any.

**Comment by sbtaylor15** [comment]
@piyush94 the dh2helm.py has been modified to default to helm3 (/usr/local/bin/helm).  To override to use helm2, set the attribute helm_exe=helm2.  This will cause dh2helm.py to do use /usr/local/bin/helm2 and perform the helm init.  Please pull the latest image.

**Comment by piyush94** [comment]
@sbtaylor15 - Thanks, Closing this for now.
