### ISSUE TITLE
ComponentType not getting set

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#297]
In DeployHub version 20200306_1708, ComponentType is not getting set from Jenkinsfile. It's going to the attributes tab.
It's working in version 20200114_1630.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we changed the attribute to look for to CompType as part of some cleanup.  We now changed it to look for ComponentType and CompType.  Please pull the latest image.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - Thanks, it's working now.

CC: @svisagan83
