### ISSUE TITLE
Global activities goes missing

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#298]
As part of deployhub cleanup, i was deleting Sub domains that come with default Deployhub installtion. After i deleted the Infrastructure sub domain from GLOBAL, Global activities go missing for other sub-domain users.
This error is there in the logs
![image](https://user-images.githubusercontent.com/11614204/76756066-0a69dd00-67ab-11ea-9149-aabbe6a66116.png)

If i recreate the sub-domain under GLOBAL, issue goes away.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 you will need to keep the GLOBAL.Infrastructure domain.  It's a special domain that is used to expose global objects to the user without following the domain parent hierarchy.  

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - Ok.

CC: @svisagan83
