### ISSUE TITLE
GLOBAL domain visible in domain dropdown

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#300]
In the recent versions, GLOBAL domain is visible in domain dropdown to sub domain users.
Due to this they are able to add users as well other objects in GLOBAL domain and gain access to all the domains.
The GLOBAL domain is not visible in version 20200114_1630.
It should not be there in the dropdown for sub-domain users.
![image](https://user-images.githubusercontent.com/11614204/76964745-3327d900-6949-11ea-9ff9-703c63af7215.png)

Thanks,
CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we removed any domains that the user is not part of the users domain and below.  
Please pull the latest image for the update.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Thanks,

CC: @svisagan83
