### ISSUE TITLE
deployments getting stuck

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#301]
Hi Steve, we have ran into a very weird issue.
Components are not getting deployed after count 33.
In /tmp i can see this
![image](https://user-images.githubusercontent.com/11614204/77333915-1ecd4d00-6d4a-11ea-81be-dfa23b04cc28.png)

no new ansible processes get created after this and log is stuck like this, everytime:
![image](https://user-images.githubusercontent.com/11614204/77333990-386e9480-6d4a-11ea-9cd8-dc622648dc6c.png)

I am also not able to stop the deployments, as i can't see any processes in the endpoint or deployhub container.

Kindly help with this on priority.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 is this only happening to one application or all applications?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 not tried with other applications. Currently this is only application of type Helm chart and with these many components.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 send us a screen shot of the component versions associated to the application version.

**Comment by piyush94** [comment]
@sbtaylor15 
![image](https://user-images.githubusercontent.com/11614204/77336477-918bf780-6d4d-11ea-9802-9518c04e639e.png)

**Comment by piyush94** [comment]
@sbtaylor15 33 might be dropzone count, as i am seeing total 33 components

**Comment by piyush94** [comment]
@sbtaylor15 the top two file and folder are getting created every second and getting deleted
![image](https://user-images.githubusercontent.com/11614204/77336991-4f16ea80-6d4e-11ea-8733-c588ab893e14.png)

I think it would be good, if we can stop the earlier deployments first.

**Comment by sbtaylor15** [comment]
@piyush94 did any of it deploy?  if so how far did it get before getting stuck?

Those two are the Ansible files being created.  The other directories are the drop zone locations.

**Comment by piyush94** [comment]
@sbtaylor15 seeing helm list output, i think upto some point it's getting deployed.
![image](https://user-images.githubusercontent.com/11614204/77337594-19becc80-6d4f-11ea-9606-76364693b3e9.png)

![image](https://user-images.githubusercontent.com/11614204/77337631-27745200-6d4f-11ea-953d-ba1114c13140.png)

In logs cacheservice is the last deployed and it matches helm list output.

**Comment by sbtaylor15** [comment]
@piyush94 - can we do a web meeting in 15 mins?  10:30 MST

**Comment by piyush94** [comment]
@sbtaylor15 ok sure.

**Comment by sbtaylor15** [comment]
@piyush94 send zoom link via email

**Comment by sbtaylor15** [comment]
@piyush94 fyi, we were able to recreate the issue.  It has to do with the number of threads.  working on a resolution.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 Great, thanks!

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 the thread limit is set in the database.  Run this query which will set the limit to 256.  Also, we are making a change to the C++ code to free up the threads.  The new exe is NOT mandatory but the query update is.

update dm.dm_engineconfig set name = 'thread_limit', value = 256;

 CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - Thanks, deployment is working now.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - Hi, today again one deployment got stuck.
thread_limit is set to 256
queue was empty
queue_wait_for was empty
No identifiable processes in container as well as endpoint.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - what was the issue and how did you solve it?

**Comment by piyush94** [comment]
@sbtaylor15 -  In assigned components, connection line was missing between two of the components.
