### ISSUE TITLE
task variables missing

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#302]
Has the option/view to add Task variables been removed. It's not there anymore in the Domains section and then after selecting a Task.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - no task variables should be there.  Can you send a screen shot?

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - ok, i zoomed out a bit, and it became visible. Horizontal scrollbar is not there.
My browser is Chrome @ 1366x768 at 0% zoom.

But it should be visible without any regards to resolution or browser zoom.

CC: @svisagan83
