### ISSUE TITLE
last deployment and completed column not having details.

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#303]
Last Deployment and Completed columns don't reflect the details even though it's there in the component version.

![image](https://user-images.githubusercontent.com/11614204/78352505-0d940400-75c6-11ea-8492-5a0adcf8d7a5.png)

![image](https://user-images.githubusercontent.com/11614204/78352549-1f75a700-75c6-11ea-9924-01b6dbca7b34.png)

Also, some UI overlapping issues are there as seen in the screenshot above.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we were able to recreate the missing column data.  Let us debug it.  Also, check your zoom level on your browser.  This will happen if you zoom in too much or shrink the screen width.  Let us know what you have your browser configured.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - My browser is Chrome 1366x768 at 0% zoom.
Also if i zoom in, the checkbox next to the component in the table gets removed.
UI overlap for current object name and tabs is happening for all the screens.

CC: @svisagan83
