### ISSUE TITLE
application version deployment issue

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#306]
Hi, we were trying the below application version setup,
![image](https://user-images.githubusercontent.com/11614204/79448945-f1e62000-7fff-11ea-9706-bfd0700f463f.png)

From an empty base version, we created three application versions which have different components from each other.

And we have one environment in which all the components will be deployed.

After one version is successfully deployed and then when we deploy another version to same environment we get this error.
![image](https://user-images.githubusercontent.com/11614204/79449205-7173ef00-8000-11ea-8434-c682b7ef509c.png)

Can you help us with this?

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 the roll forward logic recognizes that version strimzlkafka is the current version installed.  The efk is trying to be deployed but there is not relationship between the 2 versions, so the roll forward logic can't find a way to increment the deployment.  The path that exists is only backwards to the base version.

Are these docker components being deployed?  Let us know your scenario.

**Comment by piyush94** [comment]
@sbtaylor15 yes, we are trying to individually deploy these set of components to the same cluster. To make them kind of separated we created all the versions from base version. I found a workaround, if i create a new environment but still pointing to the same k8s cluster, the deployment works. So i created an environment for each of the application version.

**Comment by sbtaylor15** [comment]
@piyush94 the other way is to make each one a separate application, ie no same base version.  Then you can deploy to the same environment.

**Comment by piyush94** [comment]
@sbtaylor15 thanks, I'll look into the application requirements.
