### ISSUE TITLE
helm deployment values

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#307]
Hi, quotes are getting added around override attribute values which are true or false. Due to this `helm upgrade` is rejecting these values and deployment fails due to incorrect value.
e.g.
![image](https://user-images.githubusercontent.com/11614204/79548405-0505f800-80b3-11ea-839a-fcf7d2dcbcdc.png)

![image](https://user-images.githubusercontent.com/11614204/79548568-44ccdf80-80b3-11ea-8bb4-e89b998378c3.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we updated the dh2helm.py to remove the single and double quotes around true/false values.  Please pull the latest image for the update.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 thanks.
