### ISSUE TITLE
deleted users and groups appear in selection lists

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#308]
Deleted users and groups (status: "D") appear in selection lists where ever applicable.
Such as adding users to group and vice versa, adding users or groups to notifier, etc.
Deleted groups also appear in access specifier lists.
possible duplicate #35 

Also too many deleted objects still exist in the database. Cleanup should be done for a month or two earlier deleted objects.

**Comment by sbtaylor15** [comment]
@piyush94 the only place that we could find a deleted user was in the recipients list for a notifier.  Groups appeared to be working correctly.  Fixed the recipient panel.  Let us know what other panels are having issues.

Also, the delete objects stay in the database to preserve the audit trail.  We will look at permanently deleting objects that have been deleted and have not part of a deployment at any point.  

Please pull the latest image for the update.

**Comment by piyush94** [comment]
@sbtaylor15 - we have this group that shows status deleted.
`102	"Singularity-******-Admin_OLD"		1	"Admin AD group"	1	1	1555049254	296	1567144500	"D"		"n"	"n"	"n"	"n"	"n"	"n"`

But shows up in this panel:
![image](https://user-images.githubusercontent.com/11614204/79859372-87adf080-83ee-11ea-8003-2a84aef0097d.png)

It's not visible in Groups view. This group was created in GLOBAL domain.

Another one, this was in a sub-domain:

Issue seems to be fixed at other places. Thanks.

**Comment by sbtaylor15** [comment]
@piyush94 we fixed the delete groups appearing in the Available Groups list.  Please pull the latest image.

**Comment by piyush94** [comment]
@sbtaylor15 Thanks
