### ISSUE TITLE
add EKS and AKS support

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#310]
Hi,
As aws and azure cli are part of deployhub, is it possible to have support for deploying helm charts into, EKS and AKS respectively using credentials. So that deployhub can configure the cluster locally temporarily and deploy the helm charts.

**Comment by piyush94** [comment]
EKS example:
from creds:
aws --profile default configure set aws_access_key_id "my-20-digit-id"
aws --profile default configure set aws_secret_access_key "my-40-digit-secret-key"

from attrs:
aws eks --region "region-code" update-kubeconfig --name "cluster_name"

**Comment by piyush94** [comment]
EKS example:
from creds:
aws --profile default configure set aws_access_key_id "my-20-digit-id"
aws --profile default configure set aws_secret_access_key "my-40-digit-secret-key"

from attrs:
aws eks --region "region-code" update-kubeconfig --name "cluster_name"

**Comment by sbtaylor15** [comment]
@piyush94 Should we install aws-cli version 2.0?  Right now we are on 1.7?

**Comment by piyush94** [comment]
@sbtaylor15 Sure, should be fine.

**Comment by sbtaylor15** [comment]
**AWS Variables**

- eks.aws_access_key_id
- eks.aws_secret_access_key
- eks.region 
- eks.cluster 
- eks.optional

**AWS Commands Run**

- 'aws --profile default configure set aws_access_key_id ' + newvals['eks']['aws_access_key_id']
- 'aws --profile default configure set aws_secret_access_key ' + newvals['eks']['aws_secret_access_key']
- 'aws eks --region ' + region + ' update-kubeconfig --name ' + cluster + ' ' + optional

**Azure Variables**	
    
- aks.servicepricipal (http://ortelius-sp)
- aks.certificate (/keys/ortelius.cert)
- aks.tenant (57ebf52b-400a-4db6-a524-b07f48884433a)
- aks.resourcegroup (ortelius)
- aks.cluster (cluster1)

**Azure Command Run**

- 'az login --service-principal -u ' + serviceprincipal + ' -p ' + certificate + ' --tenant ' + tenant
- 'az aks get-credentials --resource-group ' + resourcegroup + ' --name ' + cluster

**Comment by piyush94** [comment]
@sbtaylor15 Thanks! 
Both EKS and AKS deployments are working.
There is a typo "servicepricipal" in the helm script that needs to be fixed.

Also, we would definitely need the login variables to be coming from credentials and also hidden in the log and subsequent override values.
These additions currently seem to be missing from proxy image.

**Comment by sbtaylor15** [comment]
@piyush94  Pull deployhub-rproxy:master to get the latest proxy that includes the changes.  We will re-tag to latest once the credentials have been hidden.
