### ISSUE TITLE
AlwaysDeploy issue

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#313]
If we have some component versions which had AlwaysDeploy set to Yes and then we create next component versions with AlwaysDeploy set to No, DH is still taking it as Yes and deploying it.
Component versions are being created from Jenkins.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94  Which version of DeployHub are you using for the server side?  Also, are you deploying from Jenkins or the DeployHub WebUI?

**Comment by piyush94** [comment]
@sbtaylor15 
Version | 8.0.1
Build | 20200821_1909
Database Schema: | 2020062401

The result is the same for either deploying from Jenkins or WebUI.

**Comment by sbtaylor15** [comment]
@piyush94 after doing the deployment, check the deployed components for the end point and see if the component that is has Always Deploy = N is listed.  The components on the end point is what is being checked to determine the incremental deployment.
