### ISSUE TITLE
Actions created in Sub-domains not visible

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#316]
Actions created in Sub-domains not visible during component creation.
Only GLOBAL actions visible.
Actions become visible once the component is created and then edited to set the required Action.

**Comment by sbtaylor15** [comment]
Is the admin id creating the action or an id that is in the subdomain?  Can you give an example of the domain hierarchy?

**Comment by sbtaylor15** [comment]
@piyush94 - we did find this in the latest ui version.  Please pull the "master" image for the update.

**Comment by piyush94** [comment]
@sbtaylor15 i found this in the older ui "latest" tag. It was issue for both global admin and subdomain admin.

Will you be pushing the fix to latest tag?

**Comment by sbtaylor15** [comment]
We were able to recreate it on the "master" one which has been updated.  Let us look at the older ui "latest" tag again and try to recreate it.

**Comment by sbtaylor15** [comment]
@piyush94 we found it.  Grab the updated version from "latest"
