### ISSUE TITLE
Error while creating component

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#317]
Sometimes we get error, `SyntaxError: Unexpected end of JSON input` while creating components.
After reloading the page in the browser, issue gets resolved.
![image](https://user-images.githubusercontent.com/11614204/95177647-11564c80-07dc-11eb-9562-f18bd9d95407.png)

**Comment by sbtaylor15** [comment]
Which version is this happening on?

**Comment by piyush94** [comment]
In the latest tag.

**Comment by sbtaylor15** [comment]
@piyush94 lets do a web meeting on this one.  We cannot recreate it.

**Comment by piyush94** [comment]
@sbtaylor15 can we have a call tomorrow (Friday)?
