### ISSUE TITLE
deployment from proxy ExitCode: -11

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#325]
Deployments from proxy were working a while ago but suddenly I am seeing this error in the proxy logs.
deployment stays stuck here,
![image](https://user-images.githubusercontent.com/11614204/102779767-d3200080-43ba-11eb-920c-56c9740eaf91.png)

what could be the issue here?

**Comment by piyush94** [comment]
The issue got resolved by deleting and recreating the component. What could be the reason?

**Comment by sbtaylor15** [comment]
We would need to have a copy of the database to look at the information for that component.  Let us know if you want us to debug this.

**Comment by piyush94** [comment]
This issue is happening again. I am attaching deployhub and proxy logs. Let me know if more info is required.
[deployhub-comp-deploy-issue-12-29-2020.log](https://github.com/DeployHubProject/DeployHub-Pro/files/5749810/deployhub-comp-deploy-issue-12-29-2020.log)
[deployhub-comp-deploy-issue-12-29-2020-proxy.log](https://github.com/DeployHubProject/DeployHub-Pro/files/5749811/deployhub-comp-deploy-issue-12-29-2020-proxy.log)

**Comment by piyush94** [comment]
The issue seems to be with versioning. Something is wrong with `/API/application` API endpoint. Jenkins library depends on the response from this API to get the correct latest version but that is not happening. And due to this, the versions are not getting created one below latest. Instead, version creation is random. This needs to be fixed.

After I removed the wrongly created application versions, deployment started working.

```
// Refetch parent to get version list
data = getApplication(url,userid,pw,appname,"");
def latest_appid = data[2];
```
