### ISSUE TITLE
trim attributes before saving to the DB

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#327]
If there are any space or tab characters are there at the end or beginning of either attribute name or value, they should be trimmed before being saved to the DB. Otherwise not able to edit or delete that attribute from the webapp.

**Comment by sbtaylor15** [comment]
We will add a trim on the server side before the data is saved.   Do we need to provide a sql query to cleanup existing attributes?

**Comment by piyush94** [comment]
@sbtaylor15 sure thanks. A cleanup query will be helpful.

**Comment by sbtaylor15** [comment]
Trim has been added to ui-skin-v9.0.0.3106-g3854a9f and master-v9.0.0.2945-g7ffb59b.  The database will be cleaned on startup.

**Comment by piyush94** [comment]
@sbtaylor15 thanks. fixed now.
