### ISSUE TITLE
trying out new proxy image

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#329]
Hi, got this error when trying out the new proxy image.
`Failed to exec "/opt/deployhub/engine/lib/dmtransfer": Permission denied`

UI Tag: `master-v9.0.0.2942-gd42f25b`
Proxy Tag; `ui-skin-v9.0.0.3103-g948687c`

Is it because of the UI tag?

**Comment by sbtaylor15** [comment]
@piyush94 we moved the docker build around and a different userid is building the image which cause the permissions to be incorrect.  We fixed this for the .py files, missed the dmtransfer.    Fixing it now.

**Comment by sbtaylor15** [comment]
@piyush94 the update is in ui-skin-v9.0.0.3106-g3854a9f.

**Comment by piyush94** [comment]
@sbtaylor15 Thanks, I'll give it a try later.

**Comment by piyush94** [comment]
@sbtaylor15 getting this deprecation warning when using the newer proxy images.
```
[DEPRECATION WARNING]: Distribution fedora 32 on host localhost should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/
2.9/reference_appendices/interpreter_discovery.html for more information. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by sbtaylor15** [comment]
@piyush94 we are installing python3 by default.  The python3 install is creating a symbolic link from /usr/bin/python to /usr/bin/python3.  So the future auto discovery will find python3.
