### ISSUE TITLE
using fedora minimal to reduce DH image size

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#335]
Hi @sbtaylor15 , If possible could you give a try to the fedora-minimal as the base image for DeployHub?
`registry.fedoraproject.org/fedora-minimal:32`

**Comment by piyush94** [comment]
Looks like there isn't much size difference between `fedora:32` and `fedora-minimal:32`.

**Comment by sbtaylor15** [comment]
@piyush94 most of the size is coming from the cli tools such as gcloud, az, aws etc.
