### ISSUE TITLE
clone private GIT repo

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#338]
How to clone a private GIT repo?

**Comment by sbtaylor15** [comment]
@piyush94 add a volume mount from a directory that contains your ssh keys to mount point /keys.  The entrypoint.sh will copy the ssh keys from the /keys to the correct location in the container and set the permissions accordingly.  The private Git repo should have the public ssh key associated to it.  

Import [GitCheckout Procedure](https://github.com/ortelius/ortelius/blob/main/procedures/GitCheckout.re) into Global.GitCheckout procedure.  Next add it to the Action that needs to have the clone done.

Then use the ssh or git version of the repo url (git@github.com:DeployHubProject/DeployHub-Docs.git)  for the GitRepo parameter.  GitCommit is typically the brach to switch to.  ToDirectory would be '.' (period) for current working directory.

**Comment by piyush94** [comment]
Any specific name is required for the SSH key?

**Comment by sbtaylor15** [comment]
I can't remember your git repo provider but the setup is going to be similar across providers.

GitHub uses these as default name:
* id_rsa.pub
* id_ecdsa.pub
* id_ed25519.pub

I believe you can use a different name but an update to the .ssh/config file would be required.  See [connecting-to-github-with-ssh](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh)
