### ISSUE TITLE
proxy to proxy connection

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#339]
Is it possible to connect two DH proxies to transfer artifacts and deployment instructions?

**Comment by piyush94** [comment]
Sorry, let me explain our scenario better. We want to connect two DH proxies with each other. So that one proxy can transfer artifacts and instructions to another DH proxy.

![image](https://user-images.githubusercontent.com/11614204/124754192-8d3a1c80-df47-11eb-880c-ca01fe432957.png)

**Comment by sbtaylor15** [comment]
Why the extra DH Proxy, 2 separate databases?  If the DH Proxy on the left has access to the database then it can poll the database for work to do and skip the extra DH Proxy which is doing the same polling.

**Comment by piyush94** [comment]
The reason for the extra DH Proxy is, as there will be multiple endpoints on the client side like VMs, K8s clusters, etc. instead of opening all the required ports in the firewall, we could open only DH Proxy ports.

I think we found an approach now, to allow client-side DH Proxy to connect to our on-prem DeployHub.

Thanks.
