### ISSUE TITLE
component type update issue

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#341]
We created new component types which have ids > 99. 100 and 101 respectively. When trying to assign these types to the endpoints from the UI it's not working. for 100 it's set to 0 and for 101 it's set to 1 in the table `dm_servercomptype`

After updating directly in the database it showed up correctly.

For components, it's working fine.

![image](https://user-images.githubusercontent.com/11614204/124712625-30297100-df1d-11eb-9425-d7b221e9a6d1.png)

DH version: `main-v9.0.0.2956-g908e48f`

It seems to be working in new UI: `ui-skin-v9.0.0.3173-g78c649d`
**Update: issue seems to be there in new UI as well.**

I have started working on migrating to the new UI as well. I will keep you posted on any issues I might see.

Thanks.

**Comment by sbtaylor15** [comment]
Fixed in ui-skin-v9.0.0.3178-g7df5885

**Comment by piyush94** [comment]
The issue seems to be happening when setting component type in component as well.
Also in *-Action dropdown values are repeating and some are not visible.
![image](https://user-images.githubusercontent.com/11614204/125606910-b9ef7090-055c-4370-bce7-39f7238e53ec.png)

**Comment by sbtaylor15** [comment]
Fixed the component comptype.  

ui-skin-v9.0.0.3179-g932dcc5
