### ISSUE TITLE
endpoint Key Value Configuration not working

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#343]
Endpoint Key-Value Configuration box is not working. The UI is not visible after clicking on either Add or Edit buttons.
![image](https://user-images.githubusercontent.com/11614204/125454028-9e7c8509-e479-443a-b8d9-b7529a88b825.png)

**Comment by sbtaylor15** [comment]
Fixed in ui-skin-v9.0.0.3178-g7df5885
