### ISSUE TITLE
not able to add/update/modify objects in GLOBAL domain

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#346]
Tried with multiple admin users.
Getting this error for each object:
![image](https://user-images.githubusercontent.com/11614204/133042502-ca1c98d7-f299-42b3-9a06-39180b3bc99f.png)

Error in logs:
```
Mon Sep 13 07:36:33 2021: ApiException caught e=Permission Denied
Mon Sep 13 07:36:33 2021: {"success":false,"error":"Permission Denied"}
```

Tag: `ui-skin-v9.0.0.3201-g6fabef3`

Tried in browsers, Chrome, Edge and Firefox

**Comment by sbtaylor15** [comment]
Do you have any data in Available Groups in the Access Control box?  Looks like the access control is empty.

**Comment by piyush94** [comment]
At Domains level Access Control didn't had `Administrators` group for some reason. Added that from the DB.
After that i was able to add/update objects at global level with users that are in the `Administrators` group.

Before (Firefox):
![image](https://user-images.githubusercontent.com/11614204/133388804-d1c801ff-094e-4c07-88f2-695337f96129.png)

After (Chrome):
![image](https://user-images.githubusercontent.com/11614204/133388972-8e66db32-35db-4af5-b568-c1861e258f4f.png)

Also in Firefox Domains animation/view is not appearing.
Error in console:
![image](https://user-images.githubusercontent.com/11614204/133390531-d100eefc-d0b1-4e35-9ea3-b4822c4b9f25.png)

**Comment by sbtaylor15** [comment]
We were not able to recreate the issue under Firefox, but we did make an update that may resolve the errors.  Fix is in `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3204-g071632c`

**Comment by piyush94** [comment]
Thanks but, the view is still not populating in Firefox.

**Comment by sbtaylor15** [comment]
Change the parent class to set the content-type to json/application.  Fixed the above transactions plus the /dmadminweb/Login.
Update in `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3209-g012e876`
