### ISSUE TITLE
password field not visible when creating new users

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#347]
![image](https://user-images.githubusercontent.com/11614204/133044153-934f5dfe-eccc-4b00-be53-3c2dfba54188.png)

Tag: `ui-skin-v9.0.0.3201-g6fabef3`

Tried in browsers, Chrome, Edge and Firefox

**Comment by sbtaylor15** [comment]
Fixed in `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3204-g071632c`
