### ISSUE TITLE
user getting logged out on page refresh

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#348]
Tag: `ui-skin-v9.0.0.3201-g6fabef3`

Tried in browsers, Chrome, Edge and Firefox

**Comment by sbtaylor15** [comment]
Are you logged in with LDAP user?

**Comment by piyush94** [comment]
Tried with both LDAP and local user.

**Comment by sbtaylor15** [comment]
Fixed in `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3204-g071632c`

**Comment by piyush94** [comment]
Now logout is not working, user keeps getting logged back in. Both local and LDAP.

**Comment by sbtaylor15** [comment]
The logout should delete all of the cookies and then force the login box to appear.  Try clearing your cookies, re-login and then do the logout.

**Comment by sbtaylor15** [comment]
In our test environment, the logout works correctly on Chrome, Firefox and Opera but not on Safari.  Some how the cookies are not getting cleared all the way from the cache.

**Comment by piyush94** [comment]
I tested in Chrome, Firefox and new Edge. Cookies are not getting cleared.

**Comment by sbtaylor15** [comment]
Found that the jquery function to remove cookies in no longer working.  Changed up the code to delete the cookies a different way.  Update `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3209-g012e876` has the fix.
