### ISSUE TITLE
firefox Domains view SVG issue

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#350]
The issue in Firefox is, SVG CSS style properties of height and width.

This doesn't works:
`<svg style="width: 657px; height: 657px; font: 10px sans-serif;">`

This works when height and width are set as tag attributes and not CSS properties:
`<svg height="657px" width="657px" style="font: 10px sans-serif;">`

Below tag attributes work in Chrome, Firefox and Edge as well. Kindly have a look on using the below solution.

**Comment by sbtaylor15** [comment]
Update in image: quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3227-g01b7a9e
