### ISSUE TITLE
SSL error when sending to outlook.com

### ISSUE THREAD

**Issue by sbtaylor15** [DeployHubProject/DeployHub-Pro#351]
@hatati we replaced the ssl connection logic.

Update in image:  `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3227-g01b7a9e`

**Comment by hatati** [comment]
Error still persists. Heres the error message after a failed deploy:
```
INFO: Using template "DeployFailure" to notify users
Error: Server has closed the connection
Message not okay - no recipients?
```

Recipients are present in the Notifier template and they have emails attached to them

**Comment by sbtaylor15** [comment]
Updated ssl library to resolve issue.
