### ISSUE TITLE
First Application Version not created with correct name

### ISSUE THREAD

**Issue by sbtaylor15** [DeployHubProject/DeployHub-Pro#354]
The dh python script is not creating the correct application version on first run.  Only creating the base version.

**Comment by sbtaylor15** [comment]
Extra application version is also getting created even when there are no changes to the components.  Basically, a second re-run of the same command ends up creating a second application version when it shouldn't.

**Comment by sbtaylor15** [comment]
Application version that does not have a valid parent is returned when it shouldn't.  Added code to cleanup these application versions.

**Comment by sbtaylor15** [comment]
@hatati - we made updates to both the dh python script and the backend docker image to address the application version creation.  Please use dh python version `deployhub-9.3.173` and docker image `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3268-gc2d287c`

**Comment by hatati** [comment]
I have updated the `dh` python package and the deployhub image and it seems like it's working again. The components are created as expected and the deployment succeeds.
