### ISSUE TITLE
Need to Create dir.sh

### ISSUE THREAD

**Issue by rightker** [DeployHubProject/DeployHub-Pro#62]
This is in the old bug system as OM-1832. Need to create dir.sh in C:\Program Files\OpenMake Software\Release Engineer\Engine\scripts

**Comment by rightker** [comment]
No longer required as development will proceed for Linux only. Closing this issues.

**Comment by sbtaylor15** [comment]
Still needed to have proper linux support.

**Comment by pgibbs-openmake** [comment]
Well, dir.sh is required for Linux. In any case, we're still developing for Windows and Linux. At least I hope we are!

**Comment by rightker** [comment]
Where do we stand on this?
