### ISSUE TITLE
Creating new procedure does not refresh treeview

### ISSUE THREAD

**Issue by sbtaylor15** [DeployHubProject/DeployHub-Pro#84]
Created new procedure using the Deploy category and it did not show up unless as refresh was done.

**Comment by sbtaylor15** [comment]
Failed.  Deploy category is not shown in the tree to start with.  You can see it being added but the end result is the tree is still missing it.

**Comment by pgibbs-openmake** [comment]
Working for me on both Linux and Windows builds with both Safari and Firefox.

Can you confirm which Browser you're using? When you say "You can see it being added but the end result is the tree is still missing it" can you clarify? Is the tree getting the "Deploy" category but no procedure in the category? Is the category missing? Is the procedure actually created and is visible after refresh? On creation, does the main pane show the details for the newly created procedure but the tree view has nothing selected?

**Comment by sbtaylor15** [comment]
Chrome is the browser. Use brand new fresh install. Right click on Global -> Create New Proc
Name = TestProc
Change Category to Deploy
Display Name is blank
FileName = test.sh

Hit OK.  The tree view flashes, like its being refreshed.  But no Deploy category or TestProc showing.  Refreshing the treeview manually shows everything correctly.

**Comment by pgibbs-openmake** [comment]
Interesting - Chrome works fine with the Windows back end but fails with Linux. Not sure what on earth the difference is here since all of that is done with the Java code. I'll take a look.

**Comment by pgibbs-openmake** [comment]
This *has* to be a race condition. The console.log output is identical for both operational and non-operational scenarios. My suspicion is that the ajax "newid" call is returning and attempting to refresh the tree before the database change has been commited. But the server-side code commits the change before returning the JSON result string. So something very odd is happening
